import assert from "node:assert/strict";
import {readFileSync,readdirSync} from "node:fs";
import {resolve} from "node:path";
import test from "node:test";
const root=resolve(import.meta.dirname,"..");
const read=p=>readFileSync(resolve(root,p),"utf8");
const pkg=JSON.parse(read("package.json"));
const allowed=["AGENTS.md","README.md","CONTRIBUTING.md","RELEASE.md","SECURITY.md","LICENSE","CHANGELOG.md","skills/loom/SKILL.md","skills/loom/AUTHORITY.md","skills/loom/CONSTITUTION.md","skills/loom/STORY.md","skills/loom/FINISH.md","skills/loom/PUBLISH.md","skills/loom/OMP.md","skills/loom/ORCA.md","skills/loom/CODEGRAPH.md","skills/loom-init/**","skills/loom-grill/**","skills/loom-plan/**","skills/loom-implement/**","skills/loom-verify/**","agents/**",".claude-plugin/**",".codex-plugin/**","commands/loom.md","rules/loom-verify-before-done.md","docs/authoring.md","docs/hosts.md","docs/orca.md","docs/unattended.md","docs/glossary.md","docs/workspaces.md","hooks/artifacts.cjs","hooks/boundary.cjs","hooks/verify-gate.cjs","omp-extension.mjs","opencode-plugin.mjs"];
const shipped=allowed.map(x=>x.replace(/\/\*\*$/,""));
test("package allowlist is exact and hooks contain only v7 seams",()=>{assert.deepEqual(pkg.files,allowed);assert.deepEqual(readdirSync(resolve(root,"hooks")).sort(),["artifacts.cjs","boundary.cjs","verify-gate.cjs"]);for(const stale of ["scripts/install.mjs","scripts/install-cursor","skills/loom-tend","skills/loom/TEND.md","skills/loom/UNATTENDED.md","skills/loom-plan/TO-ISSUES.md","skills/loom-plan/ISSUE-TEMPLATE.md","recipes","templates/WATCHDOG.yml","hermes-plugin","kiro-agent.json","docs/evidence"])assert.ok(!shipped.includes(stale),`stale package entry: ${stale}`)});
test("OpenCode stays a thin prose adapter",()=>{const text=read("opencode-plugin.mjs");assert.match(text,/skills\.paths/);assert.match(text,/experimental\.chat\.system\.transform/);assert.match(text,/no Loom hook\/enforcement parity|does not receive Loom's OMP runtime enforcement/);assert.doesNotMatch(text,/\.loom|session_stop|stop[- ]gate|artifacts\.cjs|boundary\.cjs|verify-gate\.cjs/)});
test("Claude and Codex manifests are prose-only",()=>{const claude=JSON.parse(read(".claude-plugin/plugin.json")),codex=JSON.parse(read(".codex-plugin/plugin.json"));assert.equal(claude.skills,"./skills/");assert.ok(Array.isArray(claude.agents)&&claude.agents.length===2);assert.equal(codex.skills,"./skills/");for(const manifest of [claude,codex])for(const key of ["hooks","runtime","enforcement","stopGate"])assert.ok(!(key in manifest),`${key} must not be advertised`)});
test("public carriers use canonical checker vocabulary",()=>{const files=["README.md","docs/hosts.md","rules/loom-verify-before-done.md","agents/loom-verify-spec.md","agents/loom-verify-standards.md",".claude-plugin/agents/loom-verify-spec.md",".claude-plugin/agents/loom-verify-standards.md"],corpus=files.map(read).join("\n");for(const term of ["Spec","Standards","APPROVE","REJECT"])assert.match(corpus,new RegExp(`\\b${term}\\b`));for(const file of files)assert.doesNotMatch(read(file),/\b(?:Tend|loom-tend)\b/) });
test("current public corpus has no removed routes or unsupported enforcement",()=>{const corpus=["AGENTS.md","README.md","CONTRIBUTING.md","RELEASE.md","SECURITY.md","docs/authoring.md","docs/hosts.md","docs/orca.md","docs/unattended.md","docs/glossary.md","opencode-plugin.mjs",".claude-plugin/plugin.json",".codex-plugin/plugin.json"].map(read).join("\n");for(const stale of ["skills/loom-tend","skills/loom/TEND.md","skills/loom/UNATTENDED.md","skills/loom-plan/TO-ISSUES.md","skills/loom-plan/ISSUE-TEMPLATE.md","recipes/","hermes-plugin","kiro-agent.json","docs/migration-v5.md","docs/migration-v6.md","docs/omp-advisor.md","scripts/install.mjs","install-cursor","install-windsurf","install-kiro","install-agents-skills"])assert.ok(!corpus.includes(stale),`public stale reference: ${stale}`);for(const phrase of ["Claude Code enforcement parity","Codex enforcement parity","OpenCode enforcement parity","Claude Code stop gate","Codex stop gate","OpenCode stop gate"])assert.ok(!corpus.includes(phrase),`unsupported claim: ${phrase}`)});

test("OMP claims only its observed callback boundaries",()=>{const omp=read("skills/loom/OMP.md"),readme=read("README.md"),hosts=read("docs/hosts.md"),rule=read("rules/loom-verify-before-done.md"),corpus=[omp,readme,hosts,rule].join("\n");assert.match(omp,/before_agent_start.*only static discipline and the exactly-seven-ritual router/);assert.match(omp,/injects no current project, Story, Ticket, repository/);assert.match(readme,/validates active artifacts and checks canonical Verify evidence on `done` Tickets/);assert.match(readme,/malformed or uninitialized.*warning/is);assert.match(readme,/No v7 host prevents a stop/);assert.match(hosts,/stale Workspace bindings for affected Tickets only/);assert.match(rule,/only runtime diagnostic Loom has/);assert.doesNotMatch(corpus,/current project pointers|action[- ]boundary enforcement|validates the active artifact fail-closed at the action boundary/);assert.doesNotMatch(corpus,/validates active artifacts fail-closed|Only OMP provides hard enforcement|block every stop attempt|remains fail-closed|supported enforcement host|only v7 enforcement host|applies fail-closed action-boundary decisions|refused by `session_stop`|before relying on enforcement/,"a prevention claim returned: session_stop forces a continuation, it never blocks")});
