import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {resolve} from "node:path";
import {spawnSync} from "node:child_process";
import test from "node:test";
import {CASES,DIMENSIONS,PILOT_BUDGET,assertBlinded,assertBudget,assertEquivalentPrompts,assertFreshApproval,buildPrompt,buildRunPlan,createBlindedPacket,dryRun,judgeVerdict,scorePilot,semanticCanary} from "../tooling/grill/pilot.mjs";
import {judgePacket,parseJudgeResponse} from "../tooling/grill/judge.mjs";
const canon=readFileSync(resolve(import.meta.dirname,"../skills/loom-grill/INTERVIEW.md"),"utf8");
test("Grill semantic canaries cover the quality contract",()=>assert.equal(semanticCanary().pass,true));
const mutations=[
 ["premise","observed failure or unmet outcome","unobserved idea"],
 ["question admission","Admit a question only when its answer can change","Ask any useful question"],
 ["dependency","Resolve prerequisite dependencies in order","Resolve dependencies later"],
 ["depth","Select the smallest depth from observed signals","Select any depth"],
 ["domain trigger","terminology, entity, relationship, or code-vocabulary signals","generic signals"],
 ["recommendation ownership","Recommendations state their evidence and consequences; the user owns the trade-off","Recommendations decide the trade-off"],
 ["proportional readback","Read back the proportional minimum","Read back anything"],
 ["stop","Stop when no admissible user-owned questions remain","Continue asking"],
 ["handoff","Objective: <resolved outcome>","Result: <resolved outcome>"],
 ["authority","Grill never writes Story, PRD, or Ticket artifacts.","Grill writes planning artifacts."]
];
for(const [name,needle,replacement] of mutations)test(`semantic canary independently rejects ${name} mutation`,()=>{const changed=canon.replace(needle,replacement);assert.notEqual(changed,canon);assert.throws(()=>semanticCanary(changed),new RegExp(name==="handoff"?"compact handoff":name));});
test("dry-run is deterministic, six-case, two-run, one-judge, bounded and model-free",()=>{const one=dryRun(),two=dryRun();assert.deepEqual(one,two);assert.equal(one.externalExecution,false);assert.equal(one.cases,6);assert.equal(one.runsPerArm,2);assert.equal(one.judges,1);assert.equal(one.maxSeconds,120);assert.equal(one.maxCostUsd,0);assert.deepEqual(one.dimensions,DIMENSIONS);});
test("prompts have exact hash parity",()=>{const a=CASES.map(c=>buildPrompt(c,"A")),b=CASES.map(c=>buildPrompt(c,"B"));assert.doesNotThrow(()=>assertEquivalentPrompts(a,b));assert.throws(()=>assertEquivalentPrompts(a,[...b.slice(0,-1),b.at(-1)+" mismatch"]),/equivalent/);});
test("blinded packet rejects identity leaks",()=>{const semanticOutput=JSON.stringify({wrongObject:"observed unmet outcome",questions:"only when answer can change",ownership:"user owns trade-off",proof:"deterministic proof seam"});const packet=createBlindedPacket({caseId:"opaque-case",prompt:"same",outputs:{A:semanticOutput,B:semanticOutput}});assert.doesNotThrow(()=>assertBlinded(packet));for(const leak of [{...packet,arm:"candidate"},{...packet,mapping:{A:"control"}}])assert.throws(()=>assertBlinded(leak),/schema|leaks/);});
test("run plan and strict external responses cover full provenance matrix",()=>{const runs=buildRunPlan();assert.equal(runs.length,24);for(const testCase of CASES){const selected=runs.filter(run=>run.caseId===testCase.id);assert.equal(selected.length,4);assert.equal(new Set(selected.map(run=>run.promptHash)).size,1);assert.equal(new Set(selected.map(run=>run.provenanceKey)).size,2);}const score=(v)=>({wrongObjectPrevention:v,prematureQuestions:v,userOwnership:v,proofClarity:v,boundaryClarity:v,readbackQuality:v,loadBearingDecisionGuardrail:v,loadBearingDecisionOpened:v===5,questionCountRationale:"independent rationale"});const responses=CASES.flatMap(testCase=>Array.from({length:2},(_,run)=>{const promptHash=buildRunPlan().find(x=>x.caseId===testCase.id).promptHash;return {caseId:testCase.id,run:run+1,promptHash,rubricVersion:"behavior-v1",scores:{A:score(4),B:score(5)},verdict:"B"};}));const result=scorePilot(responses);assert.equal(result.judgments.length,12);assert.equal(result.verdict,"B");assert.equal(result.questionCountGuardrail,"not_penalized");assert.throws(()=>scorePilot(responses.slice(1)),/count/);const duplicate=[...responses.slice(0,-1),responses[0]];assert.throws(()=>scorePilot(duplicate),/duplicate/);const undeclared=[...responses];undeclared[0]={...undeclared[0],caseId:"not-declared"};assert.throws(()=>scorePilot(undeclared),/undeclared|untrusted/);const wrongPrompt=[...responses];wrongPrompt[0]={...wrongPrompt[0],promptHash:"0".repeat(64)};assert.throws(()=>scorePilot(wrongPrompt),/prompt/);});
test("judge is a strict independent response parser",()=>{const score={wrongObjectPrevention:5,prematureQuestions:4,userOwnership:5,proofClarity:4,boundaryClarity:5,readbackQuality:4,loadBearingDecisionGuardrail:5,loadBearingDecisionOpened:true,questionCountRationale:"new decision opened"};const response={caseId:"opaque-case",run:1,promptHash:"a".repeat(64),rubricVersion:"behavior-v1",scores:{A:score,B:score},verdict:"tie"};assert.deepEqual(judgePacket(response),response);assert.deepEqual(parseJudgeResponse(JSON.stringify(response)),response);for(const malformed of [{...response,verdict:"A"},{...response,scores:{A:{...score,proofClarity:6},B:score}},{...response,scores:{A:{...score,questionCountRationale:""},B:score}}])assert.throws(()=>judgePacket(malformed),/schema|score|rationale/);});
test("pilot rejects every budget overrun",()=>{for(const key of Object.keys(PILOT_BUDGET))assert.throws(()=>assertBudget({...PILOT_BUDGET,[key]:PILOT_BUDGET[key]+1}),/budget/);});
test("approval rejects missing malformed stale future wrong scope budget and replay",()=>{const now=1_000_000,valid=()=>({issuedAt:now,interactionId:"host-interaction",scope:"grill-pilot",budget:PILOT_BUDGET});assert.throws(()=>assertFreshApproval(undefined,now),/malformed/);assert.throws(()=>assertFreshApproval({...valid(),issuedAt:"now"},now),/stale|future/);assert.throws(()=>assertFreshApproval({...valid(),issuedAt:now-30_001},now),/stale/);assert.throws(()=>assertFreshApproval({...valid(),issuedAt:now+1},now),/future/);assert.throws(()=>assertFreshApproval({...valid(),scope:"other"},now),/scope/);assert.throws(()=>assertFreshApproval({...valid(),budget:{...PILOT_BUDGET,cases:7}},now),/budget/);const token=valid();assert.equal(assertFreshApproval(token,now),true);assert.throws(()=>assertFreshApproval(token,now),/replayed/);});
test("default external execution is BLOCKED",()=>{const result=spawnSync(process.execPath,[resolve(import.meta.dirname,"../tooling/grill/pilot.mjs")],{encoding:"utf8"});assert.equal(result.status,2);assert.match(result.stderr,/BLOCKED/);});
test("dry-run has no fabricated verdict",()=>{const result=dryRun();assert.equal(result.verdict,null);assert.deepEqual(result.outputs,[]);assert.deepEqual(result.scores,[]);assert.equal(result.manifest.control.planOnly,true);assert.notEqual(result.manifest.control.commit,result.manifest.candidate.commit);});
