import assert from "node:assert/strict";
import {mkdtempSync,mkdirSync,readFileSync,rmSync,writeFileSync} from "node:fs";
import {join,resolve} from "node:path";
import {tmpdir} from "node:os";
import {createRequire} from "node:module";
import test from "node:test";
const root=resolve(import.meta.dirname,"..");
const require=createRequire(import.meta.url),artifacts=require("../hooks/artifacts.cjs");
const read=p=>readFileSync(resolve(root,p),"utf8");
const rituals={Setup:"skills/loom-init/SKILL.md",Grill:"skills/loom-grill/SKILL.md",Plan:"skills/loom-plan/SKILL.md",Implement:"skills/loom-implement/SKILL.md",Verify:"skills/loom-verify/SKILL.md",Finish:"skills/loom/FINISH.md",Publish:"skills/loom/PUBLISH.md"};
const required=["## Goal","## Inputs","## Outputs","## Process","## Hard stops","## Failure modes","## Done when"];
test("seven rituals preserve required anchors and substantive prose",()=>{for(const name of ["Setup","Grill","Plan","Implement","Verify"]){const file=rituals[name],text=read(file);for(const heading of required)assert.match(text,new RegExp(`^${heading.replace(/[.*+?^${}()|[\\]\\]/g,"\\$&")}(?:\\s+[^\\n]+)?$`,"m"),`${name} missing ${heading}`);assert.match(text,/\|[^\n]+\|[^\n]+\|/,`${name} missing decision table`);assert.ok(text.split(/\r?\n/).length>=45,`${name} prose unexpectedly small`)}for(const [name,anchors] of [["Finish",["# Explicit finish contract","## Exact intent classification","## Fixed local inventory","## Verify, instruct, and prove"]],["Publish",["# Explicit publish contract","## Exact intent and prerequisite","## Separate remote inventory","## Sequential operator execution"]]]){const text=read(rituals[name]);for(const anchor of anchors)assert.ok(text.includes(anchor),`${name} missing ${anchor}`);assert.ok(text.split(/\r?\n/).length>=35,`${name} prose unexpectedly small`)}for(const [file,floor] of [["skills/loom-plan/GRILL.md",90],["skills/loom-plan/TO-PRD.md",28],["skills/loom-plan/TO-TICKETS.md",75],["skills/loom-implement/SKILL.md",150],["skills/loom-verify/SKILL.md",150],["skills/loom-verify/TICKET-RECORD.md",28]])assert.ok(read(file).split(/\r?\n/).length>=floor,`${file} fell below preservation floor`)});
test("canonical semantic destinations remain connected",()=>{const dispatcher=read("skills/loom/SKILL.md");for(const name of Object.keys(rituals))assert.match(dispatcher,new RegExp(`\\b${name}\\b`));const plan=[read("skills/loom-plan/SKILL.md"),read("skills/loom-plan/GRILL.md"),read("skills/loom-plan/TO-PRD.md"),read("skills/loom-plan/TO-TICKETS.md")].join("\n");for(const anchor of ["Explore before asking","Gate 1","Gate 2","tracer-bullet","TICKET-TEMPLATE.md","blockedBy"])assert.ok(plan.includes(anchor),`Plan lost ${anchor}`);const verify=[read("skills/loom-verify/SKILL.md"),read("skills/loom-verify/TICKET-RECORD.md")].join("\n");for(const anchor of ["Spec","Standards","APPROVE","REJECT","Maker","Boundary"])assert.match(verify,new RegExp(`\\b${anchor}\\b`),`Verify lost ${anchor}`)});
test("owner history and cleanup preservation stay explicit",()=>{const finish=read("skills/loom/FINISH.md"),orca=read("skills/loom/ORCA.md");for(const anchor of ["traversal-safe inventory","STORY.md","optional `PRD.md`","every Ticket","relevant `CONTEXT.md` and ADR","SHA-256","semantic conflict","ADR number or filename collisions","durable pointer","post-operator bytes","commit-tree equality","service merge ref","owner commit/tree","no extra durable manifest"])assert.ok(finish.includes(anchor),`Finish lost owner-preservation anchor: ${anchor}`);assert.match(finish,/Cleanup failure or partial cleanup never rolls back, weakens, or erases/);assert.match(orca,/cleanup/i);assert.match(orca,/separate explicit|fresh exact|renewed confirmation/i)});
test("native automation safety is cross-host and bounded",()=>{const docs=read("docs/unattended.md"),omp=read("skills/loom/OMP.md"),implement=read("skills/loom-implement/SKILL.md");for(const anchor of ["every host","single-pass, finite, bounded attempt","report-only","structured result fields","silent death is forbidden","same unchanged error twice","no third identical attempt","zero findings","no project write","no commit, push","independent checker"])assert.match(docs,new RegExp(anchor.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i"),`native automation lost ${anchor}`);assert.match(omp,/unchanged error twice|no third identical attempt|bounded/i);assert.match(omp,/apply to native automation and worker attempts, not to the `session_stop` diagnostic callback/);assert.match(omp,/cannot prevent a stop/);assert.match(omp,/never fires for subagents/);assert.match(omp,/`tool_call` event returns `\{ block, reason \}`/);assert.doesNotMatch(omp,/one corrective lap|bounded exit path/);assert.match(implement,/two overlapping REJECTs|two strikes rule/i)});
test("examples and templates preserve executable detail",()=>{for(const file of ["skills/loom-plan/PRD-TEMPLATE.md","skills/loom-plan/TICKET-TEMPLATE.md","skills/loom-plan/PRODUCT-TEMPLATE.md","skills/loom-plan/DESIGN-TEMPLATE.md","skills/loom-plan/CONTEXT-FORMAT.md","skills/loom-plan/ADR-FORMAT.md"]){const text=read(file);if(!file.endsWith("TICKET-TEMPLATE.md"))assert.match(text,/^# /m);assert.match(text,/^## /m)}const tickets=read("skills/loom-plan/TO-TICKETS.md"),example=tickets.split("````markdown\n",2)[1]?.split("\n````",1)[0];assert.ok(example,"canonical Ticket example missing");const temp=mkdtempSync(join(tmpdir(),"loom-ticket-example-")),file=join(temp,".loom","filtered-csv-export","tickets","02-csv-export.md");try{mkdirSync(resolve(file,".."),{recursive:true});writeFileSync(file,example);const parsed=artifacts.parseTicket(example,file);assert.equal(parsed.id,"02-csv-export");assert.deepEqual(parsed.blockedBy,["01-report-filters"]);assert.equal(parsed.humanApproval,"not-required");const template=read("skills/loom-plan/TICKET-TEMPLATE.md"),templateFile=join(temp,".loom","story-id","tickets","01-ticket-slug.md");mkdirSync(resolve(templateFile,".."),{recursive:true});writeFileSync(templateFile,template);const materialized=artifacts.parseTicket(template,templateFile);assert.equal(materialized.id,"01-ticket-slug");assert.deepEqual(materialized.repositoryKeys,["api"])}finally{rmSync(temp,{recursive:true,force:true})}});
test("shipped prose has no references to deleted surfaces",()=>{const files=[...Object.values(rituals),"skills/loom/SKILL.md","skills/loom/AUTHORITY.md","skills/loom/CONSTITUTION.md","skills/loom/STORY.md","skills/loom/OMP.md","skills/loom/ORCA.md","skills/loom-plan/GRILL.md","skills/loom-plan/TO-PRD.md","skills/loom-plan/TO-TICKETS.md","skills/loom-plan/AMEND.md","skills/loom-implement/TDD.md","skills/loom-implement/DIAGNOSE.md"];const corpus=files.map(read).join("\n");for(const stale of ["TEND.md","UNATTENDED.md","TO-ISSUES.md","ISSUE-TEMPLATE.md","loom-tend","recipes/","hooks/stop-gate-logic.cjs"])assert.ok(!corpus.includes(stale),`shipped prose references ${stale}`)});


test("Verify prose matches the canonical runtime record",()=>{const verify=[read("skills/loom-verify/SKILL.md"),read("skills/loom-verify/TICKET-RECORD.md")].join("\n"),glossary=read("docs/glossary.md"),rule=read("rules/loom-verify-before-done.md");for(const text of [verify,glossary,rule]){assert.doesNotMatch(text,/canonical `## Verify`[^\n]*(?:executed checks|checker execution)|canonical record[^\n]*(?:checks field|checker-execution field)/i)}assert.match(verify,/no separate checks or checker-execution fields/i);assert.match(verify,/Standards evidence.*objective command\/result summaries/i);assert.match(verify,/Maker: \{stable maker identity\}[\s\S]*Spec: APPROVE\|REJECT[\s\S]*Standards: APPROVE\|REJECT[\s\S]*Human: NOT REQUIRED/)});

test("current lifecycle prose rejects removed promises",()=>{const files=[...Object.values(rituals),"skills/loom/SKILL.md","skills/loom/AUTHORITY.md","skills/loom/STORY.md","skills/loom/OMP.md","skills/loom/ORCA.md","skills/loom-plan/GRILL.md","docs/glossary.md","rules/loom-verify-before-done.md"],corpus=files.map(read).join("\n");for(const stale of ["awaiting-review","CompatibilityDecision","migrationPreview","loomRole"])assert.ok(!corpus.includes(stale),`current prose retains ${stale}`);assert.doesNotMatch(corpus,/Story (?:`open`|remains open)|keep Story open/);assert.match(read("skills/loom/STORY.md"),/current canonical `## Verify` is invalid/);assert.match(read("skills/loom/STORY.md"),/do not write an ad hoc non-canonical `STALE` block/);assert.doesNotMatch(read("skills/loom/STORY.md"),/append `STALE|appends a new verdict/)});

test("current Ticket prose uses frontmatter status and final Verify",()=>{const files=[...Object.values(rituals),"skills/loom/SKILL.md","skills/loom/AUTHORITY.md","skills/loom/CONSTITUTION.md","skills/loom/STORY.md","skills/loom/OMP.md","skills/loom/ORCA.md","agents/loom-verify-spec.md","agents/loom-verify-standards.md",".claude-plugin/agents/loom-verify-spec.md",".claude-plugin/agents/loom-verify-standards.md","docs/authoring.md","docs/orca.md","docs/glossary.md","rules/loom-verify-before-done.md"],corpus=files.map(read).join("\n");assert.doesNotMatch(corpus,/Ticket[^\n]*`## Status`|before `## Status`|excluding only ## Verify and ## Status/);assert.match([read("skills/loom-verify/SKILL.md"),read("skills/loom-verify/TICKET-RECORD.md")].join("\n"),/lifecycle frontmatter `status`/);assert.match(read("skills/loom-plan/TICKET-TEMPLATE.md"),/## Verify\n$/)});
test("current v7 prose uses Story and Ticket artifact terms",()=>{const exact={"docs/authoring.md":/\bIssue\b/,"docs/orca.md":/\b(?:issue|pack)\b/,"skills/loom/ORCA.md":/\b(?:issue|pack)\b/,"docs/authoring.md":/whole-pack confirmation/,"skills/loom-plan/GRILL.md":/\.loom\/` packs/,"skills/loom/PUBLISH.md":/pack confirmation/,"README.md":/PRD pack/};for(const [file,pattern] of Object.entries(exact))assert.doesNotMatch(read(file),pattern,`${file} retains stale artifact term`);assert.match(read("README.md"),/Story, optional material PRD, vertically sliced Tickets/) });


test("Verify preserves the full v6 review narrative in the v7 contract",()=>{
  const verify=[read("skills/loom-verify/SKILL.md"),read("skills/loom-verify/TICKET-RECORD.md")].join("\n");
  const words=verify.match(/\b[\w’'-]+\b/g)?.length??0;
  assert.ok(words>=2100,`Verify prose unexpectedly compressed: ${words} words (floor 2100)`);
  for(const heading of ["## Full chat digest output format","## Verdict","## Spec findings","## Standards findings","## Checks executed","## Sub-agent evidence","## Risk/Scope notes","## Recommended next action","## Canonical Ticket `## Verify` format","## Host limitations"])assert.ok(verify.includes(heading),`Verify lost ${heading}`);
  for(const anchor of ["What good findings look like","export skips archived rows","npm test","npm run lint","field run: 9 checkers, 199 turns","field run burned six consecutive no-op polls","silent pass, loud fail","not spawned — objective gate red","Checker yields null/empty","Conflicting Spec vs Standards","Checker tries to fix"])assert.ok(verify.includes(anchor),`Verify lost detailed narrative: ${anchor}`);
  for(const row of ["Empty diff","Objective gate red (step 2)","Parallel workers unavailable","Independent checker context unavailable","Host worker fails or yields no verdict","OMP `task` agent not found","Sub-agents unavailable","Checker yields null/empty (host glitch)","Conflicting Spec vs Standards","Checker tries to fix"])assert.match(verify,new RegExp(`\\| ${row.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")} \\|`),`Verify lost failure row: ${row}`);
  for(const row of ["Looks fine, skip sub-agents","Gates are green, skip the checkers","Checkers APPROVE, and the maker said tests pass","I'll fix it myself in Verify","Approve with known gap","Named agents probably aren't discoverable — straight to fallback"])assert.ok(verify.includes(row),`Verify lost anti-rationalization row: ${row}`);
  for(const carrier of ["| Capability | OMP | OpenCode | Claude Code | Codex |","Parallel independent sub-agents","Independent sequential fallback","Loom runtime enforcement claimed here","Multi-repository coordination"])assert.ok(verify.includes(carrier),`Verify lost capability matrix entry: ${carrier}`);
  assert.match(verify,/Ticket digest: sha256:\{64-hex digest excluding lifecycle frontmatter status and ## Verify\}[\s\S]*Human: NOT REQUIRED/);
});


test("restored core skills retain v6 operational depth without obsolete runtime theater",()=>{
  const implement=read("skills/loom-implement/SKILL.md"),setup=read("skills/loom-init/SKILL.md"),omp=read("skills/loom/OMP.md"),orca=read("skills/loom/ORCA.md"),story=read("skills/loom/STORY.md"),plan=read("skills/loom-plan/SKILL.md"),tickets=read("skills/loom-plan/TO-TICKETS.md"),grill=read("skills/loom-grill/SKILL.md");
  for(const anchor of ["Story execution preview and consent","every planned repository key","same healthy maker for REJECT rework","changed Story, Ticket set, repository, base","final report names completed, blocked"] )assert.ok(implement.includes(anchor),`Implement lost ${anchor}`);
  for(const anchor of ["single template source","one bounded setup transaction","atomic replacement","restore only bytes written by this invocation","Uncommitted control plane","newer than installed carrier"] )assert.ok(setup.includes(anchor),`Setup lost ${anchor}`);
  for(const anchor of ["Context lifecycle and recovery","smallest owning artifacts","last unresolved question","Workers receive a bounded assignment","Fields that never drop out","Capability and failure matrix","never fabricate worker output"] )assert.ok(omp.includes(anchor),`OMP lost ${anchor}`);
  for(const anchor of ["exact one-to-one set equality","Compare Orca-observed HEAD/path","coherent dirty uncommitted diff","Resume failure matrix","Handoff delta is stale","worker_done` is not idle proof"] )assert.ok(orca.includes(anchor),`Orca lost ${anchor}`);
  for(const anchor of ["semantic checkpoint is a current projection","smallest owner only","empty semantic/factual delta","every classifier explicitly","smallest owners and leave unaffected files byte-for-byte unchanged","non-canonical `STALE` block"] )assert.ok(story.includes(anchor),`Story lost ${anchor}`);
  for(const anchor of ["Planning write and recovery evidence","small exact write transaction","preserve and report the proven writes","Anti-rationalization"] )assert.ok(plan.includes(anchor),`Plan lost ${anchor}`);
  for(const anchor of ["user stories, external contracts, or Story success clauses","unaffected Ticket byte-for-byte","Horizontal layers postpone integration risk"] )assert.ok(tickets.includes(anchor),`Ticket slicing lost ${anchor}`);
  for(const anchor of ["Evidence-backed maintenance discussions","existing APPROVE is insufficient","old Tend ritual no longer exists"] )assert.ok(grill.includes(anchor),`Relocated maintenance lost ${anchor}`);
  const corpus=[implement,setup,omp,orca,story,plan,tickets,grill].join("\n");
  for(const obsolete of [".loom/workspace.json",".loom/config.json","LOOM_WITNESS","loomRole","Goal fallback","awaiting-review"])assert.ok(!corpus.includes(obsolete),`obsolete runtime theater returned: ${obsolete}`);
  assert.match(corpus,/\.loom\/local\/workspace\.json/);
  assert.match(read("docs/workspaces.md"),/owner\/control repository/);
});
