import { deepStrictEqual, equal, match, ok } from "node:assert";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
const root=resolve(dirname(fileURLToPath(import.meta.url)),".."); const require=createRequire(import.meta.url); const story=require(resolve(root,"hooks/story.cjs")); const read=(p)=>readFileSync(resolve(root,p),"utf8");

equal(story.classifyPublishIntent("/loom publish").action,"PUBLISH");
for(const phrase of ["push this story","Please create a PR for the current story.","open a hosted review for this story","release the current story"]) equal(story.classifyPublishIntent(phrase).action,"PUBLISH",phrase);
for(const phrase of ["looks good","done for now"]) equal(story.classifyPublishIntent(phrase).action,"NOOP",phrase);
for(const phrase of ["do not push this story","should we push this story?","if checks pass push this story","publish maybe","/loom publish please","push that story"]) equal(story.classifyPublishIntent(phrase).action,"ASK",phrase);
deepStrictEqual(story.classifyTendIntent("/loom tend"),{action:"TEND",mutation:false}); for(const phrase of ["tend","cleanup merged work","/loom tend please"]) equal(story.classifyTendIntent(phrase).action,"NOOP");

const lane={repository:"catalog",repositoryId:"repo-1",nativeId:"lane-1",remote:"origin",host:"github.com",branch:"feature/catalog",base:"main",commit:"abc123",tree:"tree123",checks:["npm test"],draft:false,title:"Improve catalog reliability",body:"Makes availability accurate.",finishedEvidenceExact:true,remoteSupported:true,ghAvailable:true,push:"pending",review:"pending"};
const inventory={story:{id:"catalog-reliability",lifecycle:"awaiting-review"},lanes:[lane],stopPolicy:"stop-on-first-failure"}; const preview=story.planPublishInventory(inventory);
equal(preview.action,"PREVIEW"); equal(preview.lifecycle,"awaiting-review"); equal(preview.confirmationRequired,true); ok(preview.prohibitedEffects.includes("force"));
for(const patch of [{story:{...inventory.story,lifecycle:"open"}},{lanes:[{...lane,finishedEvidenceExact:false}]},{lanes:[{...lane,title:"Loom issue 06"}]},{stopPolicy:"continue"}]) equal(story.planPublishInventory({...inventory,...patch}).action,"STOP");
const prior={...lane,push:"succeeded",review:"created"}, second={...lane,repository:"notifications",repositoryId:"repo-2",nativeId:"lane-2",branch:"feature/notifications",commit:"def456",tree:"tree456"}; const retryInput={...inventory,lanes:[prior,second]}; const retry=story.planPublishInventory(retryInput); deepStrictEqual(retry.remaining,["notifications"]);
const execute={inventory:retryInput,confirmedDigest:retry.digest,currentInventory:retryInput,results:[]}; deepStrictEqual(story.planPublishResult(execute),{action:"PUBLISH_ALLOWED",lifecycle:"awaiting-review",lanes:["notifications"]});
const success={repository:"notifications",pushAttempts:1,reviewAttempts:1,outcome:"published",publicRef:"https://github.com/example/notifications/pull/12",error:null}; equal(story.planPublishResult({...execute,results:[success]}).action,"SUCCESS");
const failed={repository:"notifications",pushAttempts:1,reviewAttempts:0,outcome:"failed",publicRef:null,error:"push rejected"}; const failure=story.planPublishResult({...execute,results:[failed]}); equal(failure.action,"FAILURE"); equal(failure.lifecycle,"awaiting-review"); equal(failure.retryRequiresRefreshedRemainingInventory,true);
equal(story.planPublishResult({...execute,currentInventory:{...retryInput,lanes:[prior,{...second,commit:"changed"}]}}).action,"STOP");
const manualLane={...lane,remoteSupported:false,ghAvailable:false}; const manualInput={...inventory,lanes:[manualLane]}; const manualPreview=story.planPublishInventory(manualInput); const manual={repository:"catalog",pushAttempts:0,reviewAttempts:0,outcome:"manual",publicRef:"Manual review bundle prepared; no supported hosted remote.",error:null}; equal(story.planPublishResult({inventory:manualInput,confirmedDigest:manualPreview.digest,currentInventory:manualInput,results:[manual]}).action,"SUCCESS");

const noGhLane={...lane,ghAvailable:false}; const noGhInput={...inventory,lanes:[noGhLane]}; const noGhPreview=story.planPublishInventory(noGhInput); equal(story.planPublishResult({inventory:noGhInput,confirmedDigest:noGhPreview.digest,currentInventory:noGhInput,results:[manual]}).action,"SUCCESS");
const published={repository:"catalog",repositoryId:"repo-1",nativeId:"lane-1",branch:"feature/catalog",base:"main",commit:"abc123",tree:"tree123",publicationRef:"https://github.com/example/catalog/pull/12",host:"github.com",remote:"origin"};
const hostProof={type:"host-merged",repository:"catalog",repositoryId:"repo-1",nativeId:"lane-1",publicationRef:published.publicationRef,headBranch:"feature/catalog",headCommit:"abc123",state:"merged",mergeCommit:"merge123",observedAt:"2026-07-23T20:00:00Z"};
const target=".loom/archive/catalog-reliability"; const contents={story:"# Catalog reliability story\nDurable product outcome.",prd:"# Product requirements\nReliable catalog behavior.",issue:"# Work item\nAcceptance is satisfied.",context:"# Context\nCatalog is the product listing.",adr:"# Decision\nUse deterministic availability."};
const artifacts=[{path:`${target}/STORY.md`,content:contents.story},{path:`${target}/PRD.md`,content:contents.prd},{path:`${target}/issues/01-work.md`,content:contents.issue},{path:`${target}/CONTEXT.md`,content:contents.context},{path:`${target}/adr/001-contract.md`,content:contents.adr}];
const publicRefs=[{repository:"catalog",repositoryId:"repo-1",nativeId:"lane-1",publicationRef:published.publicationRef}];
const owner={ownerId:"workspace-owner",git:true,archiveTarget:target,writeMode:"git-local-integration"};
const archiveInput={story:{id:"catalog-reliability",lifecycle:"awaiting-review"},publishedLanes:[published],mergeProofs:[hostProof],owner,artifacts,publicRefs,unresolvedFeedback:false}; const archive=story.planTendArchive(archiveInput); equal(archive.action,"ARCHIVE_PREVIEW"); equal(archive.archiveBeforeDone,true); equal(archive.cleanupAuthorized,false);
const digests=archive.inventory.artifacts.map(({path,contentDigest})=>({path,contentDigest})); const gitArchive={writtenArtifacts:digests,readBackArtifacts:digests,writeMethod:"git-local-integration",integration:{commit:"archive-commit",tree:"archive-tree",archiveDigest:archive.digest}};
const archiveResult={inventory:archiveInput,confirmedDigest:archive.digest,currentInventory:archiveInput,archive:gitArchive}; const done=story.planTendArchiveResult(archiveResult); equal(done.action,"DONE"); equal(done.lifecycle,"done"); equal(done.archiveReceipt.storyId,"catalog-reliability"); equal(done.archiveReceipt.lanes[0].mergeCommit,"merge123");
const localProof={type:"accepted-local-merge",repository:"catalog",repositoryId:"repo-1",nativeId:"lane-1",branch:"feature/catalog",headCommit:"abc123",targetBranch:"main",mergeCommit:"merge123",ancestryObserved:true,acceptedByUser:true,observedAt:"2026-07-23T20:00:00Z"}; equal(story.planTendArchive({...archiveInput,mergeProofs:[localProof]}).action,"ARCHIVE_PREVIEW"); equal(story.planTendArchive({...archiveInput,mergeProofs:[{...localProof,targetBranch:"release"}]}).action,"STOP");
for(const patch of [
  {mergeProofs:["host-merged"]},{mergeProofs:[{...hostProof,state:"closed"}]},{mergeProofs:[{...hostProof,publicationRef:"https://github.com/example/other/pull/9"}]},{mergeProofs:[{...hostProof,headCommit:"substituted"}]},{mergeProofs:[]},
  {publishedLanes:[published,{...published}]},{publicRefs:[{...publicRefs[0],publicationRef:"https://github.com/example/unrelated/pull/7"}]},{publicRefs:[...publicRefs,...publicRefs]},
  {owner:{...owner,archiveTarget:"../catalog-reliability"}},{owner:{...owner,archiveTarget:".loom/archive/other-story"}},
  {artifacts:artifacts.map((a)=>a.path.endsWith("STORY.md")?{...a,content:"terminal_xyz runtime session"}:a)},{artifacts:[...artifacts,{...artifacts[0]}]},{unresolvedFeedback:true}
]) equal(story.planTendArchive({...archiveInput,...patch}).action,"STOP");
for(const attack of [
  {...archiveResult,confirmedDigest:"fabricated"},{...archiveResult,currentInventory:{...archiveInput,story:{id:"other-story",lifecycle:"awaiting-review"}}},
  {...archiveResult,archive:{...gitArchive,readBackArtifacts:digests.map((x,i)=>i?x:{...x,contentDigest:"mismatch"})}},
  {...archiveResult,archive:{...gitArchive,integration:{...gitArchive.integration,archiveDigest:"fabricated"}}}
]) equal(story.planTendArchiveResult(attack).lifecycle,"awaiting-review");
const nonGitInput={...archiveInput,owner:{...owner,git:false,writeMode:"atomic-host-write"}}; const ng=story.planTendArchive(nonGitInput); equal(ng.nonGitWarning,true); equal(story.planTendArchiveResult({inventory:nonGitInput,confirmedDigest:ng.digest,currentInventory:nonGitInput,archive:{writtenArtifacts:ng.inventory.artifacts.map(({path,contentDigest})=>({path,contentDigest})),readBackArtifacts:ng.inventory.artifacts.map(({path,contentDigest})=>({path,contentDigest})),writeMethod:"atomic-host-write",integration:null}}).action,"DONE");

const currentLane={repository:"catalog",repositoryId:"repo-1",nativeId:"lane-1",selector:"lane-1",branch:"feature/catalog",head:"abc123",mergeCommit:"merge123",clean:true,inactive:true,nativePresent:true,gitWorktreePresent:true,localBranchPresent:true};
const cleanupInput={archiveInventory:archiveInput,confirmedArchiveDigest:archive.digest,currentArchiveInventory:archiveInput,archive:gitArchive,currentLanes:[currentLane]}; const cleanup=story.planTendCleanup(cleanupInput); equal(cleanup.action,"CLEANUP_PREVIEW"); equal(cleanup.actions[0].kind,"remove-worktree-then-branch"); ok(cleanup.prohibitedEffects.includes("remote-delete"));
for(const attack of [{...cleanupInput,confirmedArchiveDigest:"fabricated"},{...cleanupInput,archiveInventory:{...archiveInput,story:{id:"other-story",lifecycle:"awaiting-review"}}},{...cleanupInput,currentLanes:[{...currentLane,head:"substituted"}]},{...cleanupInput,currentLanes:[currentLane,{...currentLane}]},{...cleanupInput,currentLanes:[{...currentLane,nativePresent:false,gitWorktreePresent:true}]}]) equal(story.planTendCleanup(attack).action,"STOP");
const unsafe=story.planTendCleanup({...cleanupInput,currentLanes:[{...currentLane,clean:false}]}); equal(unsafe.action,"NOOP"); equal(unsafe.retained[0].reason,"dirty worktree");
const execution={inventory:cleanup.inventory,confirmedDigest:cleanup.digest,currentInventory:cleanup.inventory,results:[]}; equal(story.planTendCleanupResult(execution).action,"CLEANUP_ALLOWED");
const removed={repository:"catalog",repositoryId:"repo-1",nativeId:"lane-1",selector:"lane-1",branch:"feature/catalog",head:"abc123",actionKind:"remove-worktree-then-branch",removal:{command:"orca worktree rm",attempted:true,succeeded:true},absence:{orcaPresent:false,gitWorktreePresent:false},branchDeletion:{method:"git-branch-delete-merged-safe",status:"deleted"},error:null}; const cleanupDone=story.planTendCleanupResult({...execution,results:[removed]}); equal(cleanupDone.action,"SUCCESS"); equal(cleanupDone.lifecycle,"done");
for(const attack of [{...execution,confirmedDigest:"fabricated"},{...execution,currentInventory:{...cleanup.inventory,archiveReceipt:{...cleanup.inventory.archiveReceipt,storyId:"other-story"}}},{...execution,results:[{...removed,nativeId:"substituted"}]},{...execution,results:[{...removed,actionKind:"delete-branch-only"}]}]) equal(story.planTendCleanupResult(attack).action,"STOP");
const removalFailed={...removed,removal:{command:"orca worktree rm",attempted:true,succeeded:false},absence:{orcaPresent:true,gitWorktreePresent:true},branchDeletion:{method:"git-branch-delete-merged-safe",status:"not-attempted"},error:"Orca selector still present"}; equal(story.planTendCleanupResult({...execution,results:[removalFailed]}).action,"FAILURE");
for(const absence of [{orcaPresent:false,gitWorktreePresent:false},{orcaPresent:false,gitWorktreePresent:true},{orcaPresent:true,gitWorktreePresent:false}]) equal(story.planTendCleanupResult({...execution,results:[{...removalFailed,absence}]}).action,"STOP");
const branchFailed={...removed,branchDeletion:{method:"git-branch-delete-merged-safe",status:"failed"},error:"branch delete failed"}; const partial=story.planTendCleanupResult({...execution,results:[branchFailed]}); equal(partial.action,"PARTIAL"); equal(partial.completedActions[0].kind,"remove-worktree"); equal(partial.remainingActions[0].kind,"delete-branch-only");
const retryLane={...currentLane,clean:false,nativePresent:false,gitWorktreePresent:false,localBranchPresent:true}; const cleanupRetryInput={...cleanupInput,currentLanes:[retryLane]}; const retryCleanup=story.planTendCleanup(cleanupRetryInput); equal(retryCleanup.action,"CLEANUP_PREVIEW"); equal(retryCleanup.actions[0].kind,"delete-branch-only"); ok(retryCleanup.digest!==cleanup.digest,"changed action state renews confirmation");
const retryExecution={inventory:retryCleanup.inventory,confirmedDigest:retryCleanup.digest,currentInventory:retryCleanup.inventory,results:[]}; const branchOnly={repository:"catalog",repositoryId:"repo-1",nativeId:"lane-1",selector:"lane-1",branch:"feature/catalog",head:"abc123",actionKind:"delete-branch-only",removal:{attempted:false},branchDeletion:{method:"git-branch-delete-merged-safe",status:"deleted"},error:null}; equal(story.planTendCleanupResult({...retryExecution,results:[branchOnly]}).action,"SUCCESS");
const branchOnlyFailed={...branchOnly,branchDeletion:{...branchOnly.branchDeletion,status:"failed"},error:"still locked"}; const retryPartial=story.planTendCleanupResult({...retryExecution,results:[branchOnlyFailed]}); equal(retryPartial.action,"FAILURE"); equal(retryPartial.remainingActions[0].kind,"delete-branch-only");
const completed=story.planTendCleanup({...cleanupInput,currentLanes:[{...retryLane,localBranchPresent:false}]}); equal(completed.action,"NOOP"); equal(completed.completed[0].kind,"completed");
const manualDone={...manualInput,lanes:[{...manualLane,review:"manual"}]}; equal(story.planPublishInventory(manualDone).action,"NOOP");

const runtime=["skills/loom/STORY.md","skills/loom/SKILL.md","skills/loom-tend/SKILL.md","skills/loom/UNATTENDED.md","README.md","docs/workspaces.md","docs/orca.md","docs/unattended.md"].map(read).join("\n");
for(const token of ["classifyPublishIntent","planPublishInventory","planPublishResult","planTendArchive","planTendCleanup","planTendCleanupResult","awaiting-review","orca worktree rm","report-only","separate confirmation","archiveReceipt","contentDigest","accepted-local-merge"]) ok(runtime.includes(token),`missing contract ${token}`);
for(const stale of ["Finish and publish are future","publish remains separate","future explicit boundary","mergedSafe"]) ok(!runtime.includes(stale),`stale publish/Tend wording ${stale}`);
match(read("skills/loom/SKILL.md"),/classifyTendIntent/);
console.log("publish and Tend contract tests passed");
