import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import {mkdtempSync,mkdirSync,readFileSync,rmSync,symlinkSync,unlinkSync,writeFileSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {createRequire} from "node:module";
import test from "node:test";
const require=createRequire(import.meta.url),a=require("../hooks/artifacts.cjs"),b=require("../hooks/boundary.cjs"),g=require("../hooks/verify-gate.cjs");
function repo(){const root=mkdtempSync(join(tmpdir(),"loom-runtime-"));execFileSync("git",["init","-q",root]);execFileSync("git",["-C",root,"config","user.email","test@example.com"]);execFileSync("git",["-C",root,"config","user.name","Test"]);writeFileSync(join(root,"tracked"),"seed\n");execFileSync("git",["-C",root,"add","."]);execFileSync("git",["-C",root,"commit","-qm","seed"]);return root}
function ticket(root,status="ready-for-agent"){const file=join(root,".loom","alpha","tickets","01-first.md");mkdirSync(join(root,".loom","alpha","tickets"),{recursive:true});const text=`---\nid: 01-first\nstoryId: alpha\nstatus: ${status}\nblockedBy: []\n---\n\n## What to build\nBuild it.\n\n## Acceptance criteria\n- [ ] yes\n\n## Verification\nHuman approval: ${status==="ready-for-human"?"required":"not-required"}\nnode test\n\n## Verify\n`;writeFileSync(file,text);return a.parseTicket(text,file)}
const approval=(boundary,human=false)=>g.renderVerification({makerId:"maker",ticketDigest:boundary.ticketDigest,repositories:boundary.repositories,boundaryDigest:boundary.digest,spec:{verdict:"APPROVE",checkerId:"spec",evidence:"Spec matches."},standards:{verdict:"APPROVE",checkerId:"standards",evidence:"Checks pass."},human:human?{verdict:"APPROVE",checkerId:"human",evidence:"Human accepted."}:null});
test("frames avoid concatenation collisions",()=>{assert.notEqual(b.hashFrames([["a","bc"]]),b.hashFrames([["ab","c"]]));assert.notEqual(b.hashFrames([["x",Buffer.from([1,2])]]),b.hashFrames([["x",Buffer.from([1]),["x",Buffer.from([2])]]]))});
test("boundary distinguishes staged unstaged deletion and untracked",()=>{const root=repo();try{const t=ticket(root),clean=b.computeCurrentBoundary(root,t).digest;writeFileSync(join(root,"tracked"),"staged\n");execFileSync("git",["-C",root,"add","tracked"]);const staged=b.computeCurrentBoundary(root,t).digest;assert.notEqual(clean,staged);writeFileSync(join(root,"tracked"),"unstaged\n");assert.notEqual(staged,b.computeCurrentBoundary(root,t).digest);execFileSync("git",["-C",root,"reset","--hard","-q"]);unlinkSync(join(root,"tracked"));assert.notEqual(clean,b.computeCurrentBoundary(root,t).digest);execFileSync("git",["-C",root,"restore","tracked"]);writeFileSync(join(root,"fresh"),Buffer.from([0,255,1]));assert.notEqual(clean,b.computeCurrentBoundary(root,t).digest)}finally{rmSync(root,{recursive:true,force:true})}});
test("raw non-UTF8 untracked path bytes remain distinct without decoding",()=>{
  const first=[Buffer.from([0x62,0x61,0x64,0x2d,0xff])],second=[Buffer.from([0x62,0x61,0x64,0x2d,0xfe])];
  const one=b.hashFrames(b.untrackedFrames(first,()=>Buffer.from([1]))),two=b.hashFrames(b.untrackedFrames(second,()=>Buffer.from([1])));
  assert.notEqual(one,two);assert.equal(first[0][4],0xff);assert.equal(second[0][4],0xfe);
});

test("Ticket self-exclusion works tracked staged and untracked",()=>{for(const mode of ["untracked","tracked","staged","deleted"]){const root=repo();try{let t=ticket(root);if(mode!=="untracked"){execFileSync("git",["-C",root,"add",t.filePath]);execFileSync("git",["-C",root,"commit","-qm","ticket"])}const before=b.computeCurrentBoundary(root,t);if(mode==="deleted"){unlinkSync(t.filePath);assert.equal(b.computeCurrentBoundary(root,t).digest,before.digest);continue}t.sections.Verify=approval(before);writeFileSync(t.filePath,a.renderTicket(t));if(mode==="staged")execFileSync("git",["-C",root,"add",t.filePath]);t=a.parseTicket(readFileSync(t.filePath,"utf8"),t.filePath);assert.equal(b.computeCurrentBoundary(root,t).digest,before.digest);assert.equal(g.checkTicket(root,t).ok,true);t.sections["What to build"]="Changed semantics.";writeFileSync(t.filePath,a.renderTicket(t));t=a.parseTicket(readFileSync(t.filePath,"utf8"),t.filePath);assert.notEqual(b.computeCurrentBoundary(root,t).digest,before.digest)}finally{rmSync(root,{recursive:true,force:true})}}});
test("explicit Human policy survives status-only done without history",()=>{const root=repo();try{let t=ticket(root,"ready-for-human"),boundary=b.computeCurrentBoundary(root,t);t.sections.Verify=approval(boundary,false);writeFileSync(t.filePath,a.renderTicket(t));t=a.parseTicket(readFileSync(t.filePath,"utf8"),t.filePath);assert.equal(g.checkTicket(root,t).ok,false);t.sections.Verify=approval(boundary,true);writeFileSync(t.filePath,a.renderTicket(t));t=a.parseTicket(readFileSync(t.filePath,"utf8"),t.filePath);assert.equal(g.checkTicket(root,t).ok,true);t.status="done";writeFileSync(t.filePath,a.renderTicket(t));t=a.parseTicket(readFileSync(t.filePath,"utf8"),t.filePath);assert.equal(b.computeCurrentBoundary(root,t).digest,boundary.digest);assert.equal(g.checkTicket(root,t).ok,true)}finally{rmSync(root,{recursive:true,force:true})}});
test("untracked ordinary done Ticket accepts NOT REQUIRED",()=>{const root=repo();try{let t=ticket(root,"done"),boundary=b.computeCurrentBoundary(root,t);t.sections.Verify=approval(boundary);writeFileSync(t.filePath,a.renderTicket(t));t=a.parseTicket(readFileSync(t.filePath,"utf8"),t.filePath);assert.equal(g.checkTicket(root,t).ok,true)}finally{rmSync(root,{recursive:true,force:true})}});
test("Quick Verify uses an explicit non-approval Spec sentinel only with quick tier",()=>{const root=repo();try{const t=ticket(root),boundary=b.computeCurrentBoundary(root,t),text=g.renderVerification({makerId:"maker",ticketDigest:boundary.ticketDigest,repositories:boundary.repositories,boundaryDigest:boundary.digest,spec:{verdict:"NOT REQUIRED",checkerId:"Quick check",evidence:"Quick check"},standards:{verdict:"APPROVE",checkerId:"standards",evidence:"Checks pass."},human:null});assert.equal(g.checkVerification(t,text,boundary,{tier:"quick"}).ok,true);assert.equal(g.checkVerification(t,text,boundary,{tier:"behavior"}).ok,false);assert.equal(g.checkDoneTicket({...t,sections:{...t.sections,Verify:text}},{tier:"quick"}).ok,true);assert.equal(g.checkDoneTicket({...t,sections:{...t.sections,Verify:text}}).ok,false);assert.equal(g.renderVerification(g.parseVerification(text)),text)}finally{rmSync(root,{recursive:true,force:true})}});

test("canonical Verify rejects stale semantics identities evidence and malformed Human policy",()=>{const root=repo();try{const t=ticket(root),boundary=b.computeCurrentBoundary(root,t),text=approval(boundary);assert.deepEqual(text.split("\n").slice(-3),["Spec: APPROVE | spec | Spec matches.","Standards: APPROVE | standards | Checks pass.","Human: NOT REQUIRED"]);assert.deepEqual(Object.keys(g.parseVerification(text)),["makerId","ticketDigest","repositories","boundaryDigest","spec","standards","human"]);assert.equal(g.renderVerification(g.parseVerification(text)),text);assert.equal(g.checkVerification(t,text,boundary).ok,true);assert.throws(()=>g.parseVerification(text+"\nUnknown: x"));assert.throws(()=>g.parseVerification(text+"\nHuman: NOT REQUIRED"));assert.throws(()=>g.parseVerification(text.replace("Standards: APPROVE | standards | Checks pass.\n","")));assert.throws(()=>g.parseVerification(text.replace("\nHuman: NOT REQUIRED","")));assert.throws(()=>g.parseVerification(text.replace("Human: NOT REQUIRED","Human: REQUIRED")));assert.throws(()=>g.parseVerification(text.replace("Spec matches.","")));assert.equal(g.checkVerification(t,text.replace("Standards: APPROVE","Standards: REJECT"),boundary).ok,false);assert.equal(g.checkVerification(t,text.replace("| spec |","| maker |"),boundary).ok,false);const human=approval(boundary,true);assert.equal(g.checkVerification(t,human.replace("Human: APPROVE","Human: REJECT"),boundary).ok,false);assert.equal(g.checkVerification(t,human.replace("| human |","| maker |"),boundary).ok,false)}finally{rmSync(root,{recursive:true,force:true})}});

test("boundary rejects closed-shape extras",()=>{const root=repo();try{const t=ticket(root),boundary=b.computeCurrentBoundary(root,t);assert.throws(()=>b.computeBoundary(t,[{...boundary.repositories[0],extra:true}]),/repository/);assert.throws(()=>b.parseBoundary({...boundary,extra:true}),/boundary/)}finally{rmSync(root,{recursive:true,force:true})}});
test("repository keys accept safe native segments and reject invalid forms",()=>{const root=repo();try{mkdirSync(join(root,"services","api"),{recursive:true});execFileSync("git",["init","-q",join(root,"services","api")]);writeFileSync(join(root,"services","api","tracked"),"seed\n");execFileSync("git",["-C",join(root,"services","api"),"-c","user.email=test@example.com","-c","user.name=Test","add","."]);execFileSync("git",["-C",join(root,"services","api"),"-c","user.email=test@example.com","-c","user.name=Test","commit","-qm","seed"]);assert.equal(b.observeRepositories(root,["services/api"]).length,1);assert.throws(()=>b.observeRepositories(root,["api"]),/missing|ENOENT/);for(const key of ["/api","services/../api","Services/api","services//api"])assert.throws(()=>b.observeRepositories(root,[key]),/repository key invalid/)}finally{rmSync(root,{recursive:true,force:true})}});
test("repository containment rejects symlink keys",()=>{const root=repo(),outside=repo();try{symlinkSync(outside,join(root,"linked"));const t=ticket(root);t.repositoryKeys=["linked"];assert.throws(()=>b.computeCurrentBoundary(root,t),/contained real directory/)}finally{rmSync(root,{recursive:true,force:true});rmSync(outside,{recursive:true,force:true})}});
test("untracked symlink hashes target text without reading target",()=>{const root=repo(),outside=join(tmpdir(),`loom-secret-${Date.now()}`);try{writeFileSync(outside,"one");symlinkSync(outside,join(root,"link"));const one=b.repositoryDiffDigest(root);writeFileSync(outside,"two");assert.equal(b.repositoryDiffDigest(root),one);unlinkSync(join(root,"link"));symlinkSync(`${outside}-other`,join(root,"link"));assert.notEqual(b.repositoryDiffDigest(root),one)}finally{rmSync(root,{recursive:true,force:true});rmSync(outside,{force:true})}});
test("Verification policy changes stale boundary and prevents Human downgrade",()=>{const root=repo();try{let t=ticket(root,"ready-for-human"),boundary=b.computeCurrentBoundary(root,t);t.sections.Verify=approval(boundary,true);writeFileSync(t.filePath,a.renderTicket(t));t=a.parseTicket(readFileSync(t.filePath,"utf8"),t.filePath);t.status="done";t.sections.Verify=approval(boundary,false);writeFileSync(t.filePath,a.renderTicket(t));t=a.parseTicket(readFileSync(t.filePath,"utf8"),t.filePath);assert.equal(g.checkTicket(root,t).ok,false);t.sections.Verification=t.sections.Verification.replace("required","not-required");writeFileSync(t.filePath,a.renderTicket(t));t=a.parseTicket(readFileSync(t.filePath,"utf8"),t.filePath);assert.notEqual(b.computeCurrentBoundary(root,t).ticketDigest,boundary.ticketDigest)}finally{rmSync(root,{recursive:true,force:true})}});
