import { deepStrictEqual, equal, throws } from "node:assert";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");const require=createRequire(import.meta.url);const story=require(resolve(root,"hooks/story.cjs"));
const path=(name="alpha",archived=false)=>resolve("/tmp/project/.loom",...(archived?["archive",name]:[name]),"STORY.md");
const doc=({version=2,name="alpha",lifecycle="open",heading=version===2?"Current State":"Outcome"}={})=>`---\nstory: ${name}\nlifecycle: ${lifecycle}\nupdated: 2026-07-24\nversion: ${version}\n---\n## Goal\nGoal\n## ${heading}\nState\n## Decisions\n## Open Questions\n## Checks\nnpm test\n## Handoff\n## Verify\n`;
deepStrictEqual(story.parseStory(doc(),path()),{story:"alpha",lifecycle:"open",updated:"2026-07-24",version:2,archived:false,writable:true});
deepStrictEqual(story.parseStory(doc({version:1}),path("alpha",true)).writable,false);equal(story.parseStory(doc({version:1}),path()).writable,false);throws(()=>story.parseStory(doc({version:2,heading:"Outcome"}),path()),/headings differ/);
const seed=story.renderStoryV2Seed({story:"new-story",updated:"2026-07-24",goal:"Goal",currentState:"Not started",checks:"npm test"});equal(story.parseStory(seed,path("new-story")).version,2);
deepStrictEqual(story.planStoryMigration({story:{version:1,archived:false,lifecycle:"open"},writeRequested:false}).action,"READ_WITH_MIGRATION_PROPOSAL");deepStrictEqual(story.planStoryMigration({story:{version:1,archived:false,lifecycle:"open"},writeRequested:true}).action,"MIGRATION_REQUIRED");deepStrictEqual(story.planStoryMigration({story:{version:1,archived:true,lifecycle:"done"},writeRequested:true}).action,"READ");
const stories=[{name:"alpha",lifecycle:"open",activeContext:true},{name:"beta",lifecycle:"open",activeContext:false}];deepStrictEqual(story.planActiveContinuation({intent:"grill",stories,selectedStory:null}),{action:"CONTINUE",story:"alpha",route:"discuss"});equal(story.planActiveContinuation({intent:"change",stories,selectedStory:"alpha"}).route,"discuss-then-implement");equal(story.planActiveContinuation({intent:"recheck",stories,selectedStory:"alpha"}).route,"recheck");equal(story.planActiveContinuation({intent:"unrelated",stories,selectedStory:null}).action,"ORDINARY_ROUTE");equal(story.planActiveContinuation({intent:"grill",stories:stories.map(x=>({...x,activeContext:false})),selectedStory:null}).action,"ASK");
const decision={owner:"PRD",name:"retry policy",summary:"Cap retries at three"},fact={owner:"STORY",name:"Current State",summary:"Checks pass"};equal(story.planSemanticBundle({boundary:"retry behavior",decisions:[],factualUpdates:[],confirmed:false}).action,"NO_DELTA");equal(story.planSemanticBundle({boundary:"retry behavior",decisions:[decision],factualUpdates:[fact],confirmed:false}).action,"PREVIEW");deepStrictEqual(story.planSemanticBundle({boundary:"retry behavior",decisions:[decision],factualUpdates:[fact],confirmed:true}).writes,["PRD","STORY"]);equal(story.planSemanticBundle({boundary:"execution",decisions:[],factualUpdates:[fact],confirmed:false}).authority,"confirmed-execution");
const issue={name:"retry-slice",status:"done",latestVerdict:"APPROVE"};deepStrictEqual(story.planAmendment({lifecycle:"open",sameDestination:true,change:"same-slice",issue,intent:"change"}),{action:"AMEND_PRD",issueAction:"AMEND",reopen:true,stale:true,next:"implement"});equal(story.planAmendment({lifecycle:"open",sameDestination:true,change:"new-slice",issue:null,intent:"discuss"}).issueAction,"CREATE");equal(story.planAmendment({lifecycle:"done",sameDestination:true,change:"same-slice",issue,intent:"change"}).action,"LINKED_STORY");
for(const fn of [story.planActiveContinuation,story.planSemanticBundle,story.planAmendment,story.planStoryMigration]){throws(()=>fn(null),/plain object/);throws(()=>fn({}),/exactly/)}
console.log("STORY v2 continuation tests passed");
