import { deepStrictEqual, equal, match, ok, throws } from "node:assert";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
const root=resolve(import.meta.dirname,".."), ledger=JSON.parse(readFileSync(resolve(root,"docs/evidence/v6-release-ledger.json"),"utf8"));
equal(ledger.schemaVersion,1);equal(ledger.sanitized,true);deepStrictEqual(ledger.candidate,{version:"6.0.0",technicalAcceptance:"passed",independentReviews:{spec:"APPROVE",standards:"APPROVE"},unresolvedBlockers:[],releaseAuthorized:true});ok(Array.isArray(ledger.receipts)&&ledger.receipts.length>0);
const allowed=new Set(["observed-native","simulated/planner","blocked","not exercised"]);
for(const [i,r] of ledger.receipts.entries()){deepStrictEqual(Object.keys(r).sort(),["action","digest","observedAt","provenance","repositories","story","summary","technicalAcceptance","unresolvedBlocker"].sort());ok(allowed.has(r.provenance),`receipt ${i} provenance`);match(r.digest,/^[a-f0-9]{64}$/);match(r.observedAt,/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/);equal(typeof r.technicalAcceptance,"boolean");equal(r.provenance==="observed-native",r.technicalAcceptance);equal(r.provenance==="blocked",typeof r.unresolvedBlocker==="string");for(const value of Object.values(r))if(typeof value==="string"){ok(!/(?:\/Users\/|\.loom\/|task_[a-z0-9]|terminal_[a-z0-9]|session_[a-z0-9])/i.test(value),`receipt ${i} leaks private/raw identifier`);}}
const observed=(action,summary,story,repositories)=>ledger.receipts.some(r=>r.provenance==="observed-native"&&action.test(r.action)&&summary.test(r.summary)&&story.test(r.story)&&repositories.test(r.repositories));
const requireComplete=(candidate)=>{
  const rs=candidate.receipts;
  const has=(provenance,action,summary,story,repositories)=>rs.some(r=>provenance.test(r.provenance)&&action.test(r.action)&&summary.test(r.summary)&&story.test(r.story)&&repositories.test(r.repositories));
  ok(has(/^observed-native$/, /four isolated Orca-owned service lanes/i, /all logical lanes visible and independently addressed/i, /Alpha, Beta/i, /catalog, notifications/i),"two Stories/two services isolated topology required");
  ok(has(/^observed-native$/, /bounded tasks with explicit input\/output\/limits/i, /dependency remained pending until predecessor worker completion/i, /Alpha, Beta/i, /catalog, notifications/i),"bounded delegation and dependency wait required");
  ok(has(/^observed-native$/, /compressed .* durable/i, /independent checks reported PASS/i, /Alpha, Beta/i, /catalog, notifications/i),"compressed fix, durable change, and independent Verify required");
  ok(has(/^observed-native$/, /Rethought accepted .* targeted recheck/i, /evidence became stale.*not rerun.*targeted recheck completed/i, /Alpha/i, /catalog/i),"rethink and targeted recheck required");
  ok(has(/^observed-native$/, /local Finish commits/i, /no push occurred during Finish/i, /Alpha, Beta/i, /catalog, notifications/i),"local Finish without push required");
  ok(has(/^observed-native$/, /publish.*failed non-fast-forward.*refreshed inventory/i, /First published ref remained.*failed lane remained local.*no replay/i, /Alpha, Beta/i, /catalog, notifications/i),"partial Publish failure, refresh, and no replay required");
  ok(has(/^observed-native$/, /local notifications .* accepted .* merge.*archive.*worktree rm/i, /Accepted-local-merge ancestry.*reconciliation.*archive.*cleanup/i, /Beta recovery/i, /notifications, owner/i),"accepted-local merge Tend/archive required");
  ok(has(/^observed-native$/, /selective .* cleanup/i, /lane.*remained.*only .* lane was removed/i, /Other surviving Story/i, /catalog, owner/i),"selective cleanup with neighbor survival required");
  ok(has(/^observed-native$/, /mismatched identity selector.*stale.*absent/i, /failed before mutation/i, /Alpha, Beta/i, /owner, catalog, notifications/i),"mismatch, stale, and absent denials required");
  ok(has(/^observed-native$/, /exact attended cleanup authority/i, /stale evidence, absent authority, and over-broad targets returned `DENY`/i, /Beta recovery/i, /notifications/i),"over-broad guarded denial required");
  ok(has(/^observed-native$/, /fresh OMP session/i, /no inherited.*authority.*no edit, commit, push/i, /Beta recovery/i, /notifications, owner/i),"fresh reconstruction without inherited authority required");
  ok(has(/^not exercised$/, /context-pressure shake/i, /no measurable pressure\/shake capability.*fresh reconstruction/i, /Beta recovery/i, /notifications/i),"shake N/A fallback required");
  ok(has(/^blocked$/, /Durable Story semantics/i, /cannot be claimed observed/i, /Alpha, Beta/i, /catalog, notifications/i),"prior durable checkpoint blocker must remain");
  ok(has(/^blocked$/, /over-broad cleanup guard probe/i, /succeeded instead of denying/i, /Beta/i, /notifications/i),"prior overbroad blocker must remain");
  ok(has(/^blocked$/, /Tend reconciliation\/archive/i, /must not be described as complete Tend/i, /Alpha/i, /catalog, notifications/i),"prior Tend blocker must remain");
  ok(has(/^blocked$/, /Final release approval/i, /later independently APPROVED.*resolving this historical gate/i, /Alpha, Beta/i, /none/i),"historical final-review observation must remain and record its later resolution");
};
requireComplete(ledger);
throws(()=>requireComplete({...ledger,receipts:ledger.receipts.slice(0,3)}),"synthetic three-row ledger must fail");
ok(observed(/four isolated Orca-owned service lanes/i,/independently addressed/i,/Alpha, Beta/i,/catalog, notifications/i));
ok(ledger.receipts.some(r=>r.provenance==="observed-native"),"observed-native receipts required");ok(ledger.receipts.some(r=>r.provenance==="blocked"),"earlier blocked events must remain");const shake=ledger.receipts.find(r=>r.provenance==="not exercised"&&/context-pressure shake/i.test(r.action));ok(shake&&/no measurable pressure\/shake capability/i.test(shake.summary)&&/fresh reconstruction/i.test(shake.summary),"shake N/A requires capability reason and fallback");ok(ledger.receipts.some(r=>r.provenance==="observed-native"&&/fresh OMP session/i.test(r.action)&&/no inherited/i.test(r.summary)),"fresh same-worktree reconstruction with no inherited authority required");
console.log("v6 live pilot receipt tests passed");
