import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import {mkdtempSync,mkdirSync,readFileSync,rmSync,writeFileSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {createRequire} from "node:module";
import test from "node:test";
const require=createRequire(import.meta.url),a=require("../hooks/artifacts.cjs"),b=require("../hooks/boundary.cjs"),g=require("../hooks/verify-gate.cjs");
function repo(){const root=mkdtempSync(join(tmpdir(),"loom-ws-"));execFileSync("git",["init","-q",root]);execFileSync("git",["-C",root,"config","user.email","test@example.com"]);execFileSync("git",["-C",root,"config","user.name","Test"]);writeFileSync(join(root,"seed"),"seed\n");execFileSync("git",["-C",root,"add","."]);execFileSync("git",["-C",root,"commit","-qm","seed"]);return root}
function ownerFixture(){const root=repo();mkdirSync(join(root,".loom","alpha","tickets"),{recursive:true});writeFileSync(join(root,".loom","version"),"7\n");writeFileSync(join(root,".loom","alpha","STORY.md"),"---\nid: alpha\ntitle: Alpha\nstatus: active\n---\n\n## Intent\nIntent.\n\n## Success\n- ok\n\n## Decisions\nSmall.\n");return root}
const wsTicket=(id="01-first",keys="[api]")=>`---\nid: ${id}\nstoryId: alpha\nstatus: ready-for-agent\nblockedBy: []\nrepositoryKeys: ${keys}\n---\n\n## What to build\nBuild.\n\n## Acceptance criteria\n- [ ] yes\n\n## Verification\nHuman approval: not-required\nnode test\n\n## Verify\n`;
const binding=(id="payments",entries=[{repositoryKey:"api",orcaRepositoryId:"repo-api"}])=>JSON.stringify({schemaVersion:1,workspaceId:id,bindings:entries},null,2)+"\n";
test("parses and renders local Workspace bindings",()=>{const parsed=a.parseWorkspaceBindings(binding(),join(tmpdir(),"workspace.json"));assert.equal(parsed.workspaceId,"payments");assert.deepEqual(parsed.bindings,[{repositoryKey:"api",orcaRepositoryId:"repo-api"}]);assert.equal(a.renderWorkspaceBindings(parsed),binding())});
test("accepts local binding directory and rejects root workspace.json",()=>{const root=ownerFixture();try{mkdirSync(join(root,".loom","local"),{recursive:true});writeFileSync(join(root,".loom","local","workspace.json"),binding());writeFileSync(join(root,".loom","alpha","tickets","01-first.md"),wsTicket());const loom=a.loadLoom(root);assert.equal(loom.mode,"workspace");assert.equal(loom.workspaceId,"payments");writeFileSync(join(root,".loom","workspace.json"),"{}");assert.throws(()=>a.loadLoom(root),/unknown entry workspace.json/)}finally{rmSync(root,{recursive:true,force:true})}});
test("Workspace Tickets require logical repositoryKeys",()=>{const root=ownerFixture();try{mkdirSync(join(root,".loom","local"),{recursive:true});writeFileSync(join(root,".loom","local","workspace.json"),binding());writeFileSync(join(root,".loom","alpha","tickets","01-first.md"),wsTicket("01-first","[.]"));assert.throws(()=>a.loadLoom(root),/logical repositoryKeys/);writeFileSync(join(root,".loom","alpha","tickets","01-first.md"),wsTicket("01-first","[services/api]"));assert.throws(()=>a.loadLoom(root),/logical repositoryKeys/)}finally{rmSync(root,{recursive:true,force:true})}});
test("stale binding blocks only affected Tickets",()=>{const owner=ownerFixture(),api=repo(),web=repo();try{mkdirSync(join(owner,".loom","local"),{recursive:true});writeFileSync(join(owner,".loom","local","workspace.json"),binding("payments",[{repositoryKey:"api",orcaRepositoryId:"repo-api"},{repositoryKey:"web",orcaRepositoryId:"repo-web"}]));writeFileSync(join(owner,".loom","alpha","tickets","01-api.md"),wsTicket("01-api","[api]"));writeFileSync(join(owner,".loom","alpha","tickets","02-web.md"),wsTicket("02-web","[web]"));const paths={api,web};const loom=a.loadLoom(owner,{resolveRepository:key=>{if(key==="api")throw new Error("stale Orca repository");return paths[key]}});assert.deepEqual(loom.bindingState.affectedTickets,["alpha/01-api"]);assert.deepEqual(loom.readyTickets,[{storyId:"alpha",id:"02-web"}]);const dash=loom.dashboard();assert.equal(dash.readyTickets.length,1);assert.equal(dash.stories[0].tickets.find(x=>x.ticketId==="01-api").blockedByBinding,true);assert.equal(dash.stories[0].tickets.find(x=>x.ticketId==="02-web").blockedByBinding,false)}finally{rmSync(owner,{recursive:true,force:true});rmSync(api,{recursive:true,force:true});rmSync(web,{recursive:true,force:true})}});
test("logical repository keys observe external service repos",()=>{const owner=ownerFixture(),api=repo();try{mkdirSync(join(owner,".loom","local"),{recursive:true});writeFileSync(join(owner,".loom","local","workspace.json"),binding());writeFileSync(join(owner,".loom","alpha","tickets","01-first.md"),wsTicket());const ticket=a.loadLoom(owner,{resolveRepository:()=>api}).tickets[0];writeFileSync(join(api,"service"),"change\n");const boundary=b.computeCurrentBoundary(owner,ticket,{resolveRepository:()=>api});assert.equal(boundary.repositories[0].key,"api");assert.notEqual(boundary.repositories[0].diffDigest,b.hashFrames([["staged",Buffer.alloc(0)],["unstaged",Buffer.alloc(0)],["untracked.count","0"]]));const approval=g.renderVerification({makerId:"maker",ticketDigest:boundary.ticketDigest,repositories:boundary.repositories,boundaryDigest:boundary.digest,spec:{verdict:"APPROVE",checkerId:"spec",evidence:"ok"},standards:{verdict:"APPROVE",checkerId:"standards",evidence:"ok"},human:null});ticket.sections.Verify=approval;assert.equal(g.checkTicket(owner,ticket,{resolveRepository:()=>api}).ok,true)}finally{rmSync(owner,{recursive:true,force:true});rmSync(api,{recursive:true,force:true})}});
test("done Ticket stop-gate checks canonical evidence not live Git",()=>{const owner=ownerFixture(),api=repo();try{mkdirSync(join(owner,".loom","local"),{recursive:true});writeFileSync(join(owner,".loom","local","workspace.json"),binding());writeFileSync(join(owner,".loom","alpha","tickets","01-first.md"),wsTicket());let ticket=a.loadLoom(owner,{resolveRepository:()=>api}).tickets[0];const boundary=b.computeCurrentBoundary(owner,ticket,{resolveRepository:()=>api});ticket.sections.Verify=g.renderVerification({makerId:"maker",ticketDigest:boundary.ticketDigest,repositories:boundary.repositories,boundaryDigest:boundary.digest,spec:{verdict:"APPROVE",checkerId:"spec",evidence:"ok"},standards:{verdict:"APPROVE",checkerId:"standards",evidence:"ok"},human:null});ticket.status="done";writeFileSync(ticket.filePath,a.renderTicket(ticket));ticket=a.parseTicket(readFileSync(ticket.filePath,"utf8"),ticket.filePath,true);writeFileSync(join(api,"later-change"),"x\n");assert.equal(g.checkDoneTicket(ticket).ok,true);assert.equal(g.checkTicket(owner,ticket,{resolveRepository:()=>api}).ok,false)}finally{rmSync(owner,{recursive:true,force:true});rmSync(api,{recursive:true,force:true})}});
