#!/usr/bin/env node
import { access, cp, lstat, mkdtemp, mkdir, readFile, realpath, rm, writeFile } from "node:fs/promises";
import { constants, existsSync } from "node:fs";
import { dirname, isAbsolute, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";
import { execFile as childExecFile } from "node:child_process";
import { promisify } from "node:util";
import { closedPath, redact, resolveOmpRuntimeClosure } from "../shared.mjs";
export { redact } from "../shared.mjs";
const execFile=promisify(childExecFile), TIMEOUT=30000, CARRIERS=["omp","claude","opencode","codex"];
const REPOSITORY_ROOT=resolve(dirname(fileURLToPath(import.meta.url)),"../..");
const result=(carrier,fields)=>({carrier,...fields,stdout:redact(fields.stdout||""),stderr:redact(fields.stderr||"")});
const command=async(file,args,options,deps)=>{try{const out=await deps.exec(file,args,{...options,timeout:TIMEOUT,windowsHide:true});return{code:0,stdout:String(out.stdout||""),stderr:String(out.stderr||"")};}catch(error){return{code:typeof error.code==="number"?error.code:1,stdout:String(error.stdout||""),stderr:String(error.stderr||error.message||"")};}};
const parseJson=text=>{try{return JSON.parse(text);}catch{return null;}};
const SYSTEM_DIRS=Object.freeze(["/usr/bin","/bin","/usr/sbin","/sbin"]);
export const childPath=(executable,runtimeExecutable)=>closedPath(executable,runtimeExecutable,SYSTEM_DIRS);
const envFor=(root,executable,runtimeExecutable)=>({OMP_EXECUTABLE:executable||"",PATH:childPath(executable,runtimeExecutable),HOME:join(root,"home"),XDG_CONFIG_HOME:join(root,"config"),XDG_DATA_HOME:join(root,"data"),XDG_CACHE_HOME:join(root,"cache"),LANG:"C.UTF-8",LC_ALL:"C.UTF-8",TZ:"UTC"});
export const executable=async(name,deps,override=name==="omp"?process.env.OMP_EXECUTABLE:undefined)=>{let path=override;if(path!==undefined&&!isAbsolute(path))throw Error("OMP_EXECUTABLE must be an absolute executable path");if(path===undefined){const probe=await command("/usr/bin/which",[name],{env:{PATH:process.env.PATH||""}},deps);path=probe.stdout.trim().split(/\r?\n/)[0]}if(!isAbsolute(path))throw Error(name+" executable must resolve to an absolute path");try{await (deps.access||access)(path,constants.X_OK);return path}catch{throw Error(name+" executable is not executable: "+path)}};
const ompList=payload=>{const entries=Array.isArray(payload)?payload:payload?.plugins||payload?.npm||[];return entries.find(item=>item?.name==="loom"||item?.manifest?.name==="loom")};
const ensureRoots=root=>Promise.all(["home","config","data","cache","project","sources"].map(name=>mkdir(join(root,name),{recursive:true})));
async function materialize(source,target,paths){await mkdir(target,{recursive:true});for(const path of paths){const from=join(source,path);if(existsSync(from))await cp(from,join(target,path),{recursive:true});}return target;}
async function ompSmoke({source,root,env,deps,fixture}){const project=join(root,"project"),cli=env.OMP_EXECUTABLE,copy=await materialize(source,join(root,"sources","omp"),["package.json",".claude-plugin","skills","agents"]),expected=parseJson(await readFile(join(source,"package.json"),"utf8"));if(fixture==="malformed")await writeFile(join(copy,"package.json"),"{ malformed fixture\n");const install=await command(cli,["plugin","install","--local","--scope","project",copy,"--json"],{cwd:project,env},deps),listed=await command(cli,["plugin","list","--json"],{cwd:project,env},deps),observed=ompList(parseJson(listed.stdout));let mutation=null;if(fixture==="missing")mutation=await command(cli,["plugin","uninstall","loom","--json"],{cwd:project,env},deps);if(fixture==="disabled")mutation=await command(cli,["plugin","disable","loom","--json"],{cwd:project,env},deps);const after=mutation?await command(cli,["plugin","list","--json"],{cwd:project,env},deps):listed,afterObserved=ompList(parseJson(after.stdout));const fixtureObserved=fixture==="malformed"?(install.code!==0||listed.code!==0||!observed):!mutation||(mutation.code===0&&((fixture==="missing"&&!afterObserved)||(fixture==="disabled"&&afterObserved?.enabled!==true)));const observedVersion=observed?.version??observed?.manifest?.version,validVersion=typeof observedVersion==="string"&&/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(observedVersion),identity=Boolean(observed)&&(observed?.name==="loom"||observed?.manifest?.name==="loom")&&observed?.enabled===true&&validVersion&&observedVersion===expected?.version;const pass=!fixture&&install.code===0&&listed.code===0&&identity;return result("omp",{Result:pass?"PASS":"FAIL",Changed:fixture==="malformed"?"owned disposable copy with malformed package metadata":mutation?"isolated install plus native "+fixture:"isolated install",Check:"native install/list with enabled identity/version readback"+(fixture==="malformed"?"; host must reject or not discover malformed source":mutation?" + "+fixture+"/list":""),"Next action":pass?"retain evidence":fixture&&fixtureObserved?"fixture correctly rejected by smoke":"inspect authoritative state transitions",stdout:[install,listed,mutation,after].filter(Boolean).map(x=>x.stdout).join("\n"),stderr:[install,listed,mutation,after].filter(Boolean).map(x=>x.stderr).join("\n")})}
const claudeEntry=payload=>Array.isArray(payload)?payload.find(item=>item?.id==="loom@loom"):null;
const marketplaceEntry=payload=>Array.isArray(payload)?payload.find(item=>item?.name==="loom"):null;
async function claudeSmoke({source,root,env,deps,executable,fixture}){const project=join(root,"project"),copy=await materialize(source,join(root,"sources","claude"),[".claude-plugin","skills","agents","package.json"]),manifest=join(copy,".claude-plugin","plugin.json");if(fixture==="malformed")await writeFile(manifest,"{ malformed fixture\n");const add=await command(executable,["plugin","marketplace","add",copy],{cwd:project,env},deps),install=await command(executable,["plugin","install","loom@loom","--scope","user"],{cwd:project,env},deps),listed=await command(executable,["plugin","list","--json"],{cwd:project,env},deps),markets=await command(executable,["plugin","marketplace","list","--json"],{cwd:project,env},deps);let mutation=null;if(fixture==="missing")mutation=await command(executable,["plugin","uninstall","loom@loom","--scope","user"],{cwd:project,env},deps);if(fixture==="disabled")mutation=await command(executable,["plugin","disable","loom@loom","--scope","user"],{cwd:project,env},deps);const after=mutation?await command(executable,["plugin","list","--json"],{cwd:project,env},deps):listed,entry=claudeEntry(parseJson(listed.stdout)),afterEntry=claudeEntry(parseJson(after.stdout)),market=marketplaceEntry(parseJson(markets.stdout));const expectedVersion=parseJson(await readFile(join(source,".claude-plugin","plugin.json"),"utf8"))?.version;const identity=entry?.version===expectedVersion&&entry?.scope==="user"&&entry?.enabled===true&&market?.source==="directory"&&resolve(market?.path||"")===resolve(copy);const fixtureObserved=fixture==="malformed"?(add.code!==0||install.code!==0):fixture==="missing"?mutation?.code===0&&!afterEntry:fixture==="disabled"?mutation?.code===0&&afterEntry?.enabled===false:true;const pass=!fixture&&add.code===0&&install.code===0&&listed.code===0&&markets.code===0&&identity;return result("claude",{Result:pass?"PASS":"FAIL",Changed:fixture?"disposable marketplace/install plus "+fixture:"disposable marketplace and user-scope install",Check:"marketplace add/install/list --json + marketplace identity"+(mutation?" + mutation/list":""),"Next action":pass?"retain authoritative install evidence":fixtureObserved?"fixture correctly rejected by smoke":"inspect Claude authoritative state",stdout:[add,install,listed,markets,mutation,after].filter(Boolean).map(x=>x.stdout).join("\n"),stderr:[add,install,listed,markets,mutation,after].filter(Boolean).map(x=>x.stderr).join("\n")})}
async function opencodeSmoke({source,root,env,deps,executable}){const project=join(root,"project"),copy=await materialize(source,join(root,"sources","opencode"),["package.json","opencode-plugin.mjs","skills"]),installed=await command(executable,["plugin",copy],{cwd:project,env},deps),help=await command(executable,["plugin","--help"],{cwd:project,env},deps);if(existsSync(join(source,".opencode")))throw Error("OpenCode left .opencode residue in live source checkout");return result("opencode",{Result:"N/A",Changed:"disposable source copy/project only; generated state removed",Check:"opencode plugin <disposable local copy>; plugin --help exposes no list/discovery query","Next action":"N/A: observed CLI exposes install/config mutation but no authoritative enabled/discovered readback",stdout:installed.stdout+"\n"+help.stdout,stderr:installed.stderr+"\n"+help.stderr})}
const unavailable=(carrier,next,stdout="",stderr="",check="availability and local load/discovery seam probe")=>result(carrier,{Result:"N/A",Changed:"none",Check:check,"Next action":next,stdout,stderr});
async function codexSmoke({root,env,deps,executable}){const check=await command(executable,["plugin","--help"],{cwd:join(root,"project"),env},deps);return unavailable("codex","N/A: executable exists; `codex plugin --help` was probed, but no stable local scratch load/discovery seam is claimed",check.stdout,check.stderr,"`codex plugin --help` executable seam probe (exit "+check.code+")") }
export const CARRIER_REGISTRY=Object.freeze({codex:{required:false,sourcePaths:[".codex-plugin/","skills/","commands/"],source:".codex-plugin/ + skills/ + commands/",owner:"Codex availability and local scratch seam probe",run:codexSmoke},omp:{required:true,sourcePaths:["package.json",".claude-plugin/","skills/","agents/"],source:"package.json + .claude-plugin/ + skills/ + agents/",owner:"OMP local plugin install and JSON plugin list",run:ompSmoke},claude:{required:true,sourcePaths:["package.json",".claude-plugin/","skills/","agents/"],source:"package.json + .claude-plugin/ + skills/ + agents/",owner:"Claude local marketplace install and authoritative JSON list",run:claudeSmoke},opencode:{required:false,sourcePaths:["package.json","opencode-plugin.mjs","skills/"],source:"package.json + opencode-plugin.mjs + skills/",owner:"OpenCode disposable local install; no authoritative list seam",run:opencodeSmoke}});
export function carriersForChangedPaths(paths){return CARRIERS.filter(carrier=>CARRIER_REGISTRY[carrier].sourcePaths.some(prefix=>paths.some(path=>{path=path.replace(/^\.\//,"");return path===prefix||(prefix.endsWith("/")&&path.startsWith(prefix))})))}
export async function validateSource(source,{expectedRoot=REPOSITORY_ROOT}={}){if(typeof source!=="string"||!isAbsolute(source))throw Error("source must be an absolute path");const stat=await lstat(source).catch(()=>null);if(!stat)throw Error("source does not exist");if(stat.isSymbolicLink())throw Error("source must not be a symlink");if(!stat.isDirectory())throw Error("source must be a directory");const root=await realpath(resolve(expectedRoot)),candidate=await realpath(resolve(source));if(candidate!==root&&!candidate.startsWith(root+sep))throw Error("source must be inside expected repository root");return candidate}
async function repositoryStatus(deps){return command("/usr/bin/git",["-C",REPOSITORY_ROOT,"status","--porcelain=v1","--untracked-files=all"],{env:process.env},deps)}
export async function runSmoke({carriers=CARRIERS,source=REPOSITORY_ROOT,scratch=true,fixture,deps={}}={}){if(!scratch)throw Error("--scratch is required: carrier smokes must be disposable");await validateSource(source);if(fixture&&!['missing','malformed','disabled'].includes(fixture))throw Error("fixture must be missing, malformed, or disabled");const owned=await mkdtemp(join(tmpdir(),"loom-carrier-smoke-")),d={exec:execFile,rm,access,...deps},before=await repositoryStatus(d);try{await ensureRoots(owned);const records=[];for(const carrier of carriers){const adapter=CARRIER_REGISTRY[carrier];if(!adapter)throw Error("unknown carrier: "+carrier);let path;try{path=await executable(carrier,d)}catch(error){const searched=carrier+" executable absent; searched with `/usr/bin/which "+carrier+"` on PATH="+(process.env.PATH||"")+"; "+error.message;records.push(result(carrier,{Result:"N/A",Changed:"none",Check:"UNAVAILABLE: `/usr/bin/which "+carrier+"` and executable access check", "Next action":"N/A: environment unavailable; this does not prove the carrier seam is absent",stdout:"",stderr:searched}));continue}let runtimeExecutable;if(carrier==="omp"){try{({runtimeExecutable}=await resolveOmpRuntimeClosure({ompExecutable:path,exec:d.exec,checkExecutable:candidate=>(d.access||access)(candidate,constants.X_OK),systemDirs:SYSTEM_DIRS,probe:async childPath=>{const probe=await command(path,["--version"],{env:{PATH:childPath}},d);if(probe.code!==0)throw Error(probe.stderr||"OMP version probe failed");return probe.stdout;}}));}catch(error){records.push(result(carrier,{Result:"N/A",Changed:"none",Check:"UNAVAILABLE: OMP executable closure probe", "Next action":"install the concrete OMP launcher prerequisite or a self-contained OMP",stdout:"",stderr:error.message}));continue}}records.push(await adapter.run({source,root:owned,env:envFor(owned,path,runtimeExecutable),fixture,executable:path,deps:d}));}const after=await repositoryStatus(d);if(before.code!==0||after.code!==0||before.stdout!==after.stdout)throw Error("source checkout status changed during carrier smoke");if(existsSync(join(REPOSITORY_ROOT,".opencode")))throw Error("live source checkout contains .opencode residue");return records;}finally{await d.rm(owned,{recursive:true,force:true});}}
export function releaseFailed(records){return records.some(record=>record.Result==="FAIL"||(CARRIER_REGISTRY[record.carrier]?.required&&record.Result!=="PASS"));}
function args(argv){if(!argv.includes("--all")||!argv.includes("--scratch"))throw Error("usage: --all --scratch [--json] [--fixture missing|malformed|disabled]");const index=argv.indexOf("--fixture");return{carriers:CARRIERS,source:REPOSITORY_ROOT,scratch:true,fixture:index<0?undefined:argv[index+1],json:argv.includes("--json")};}
if(process.argv[1]&&resolve(process.argv[1])===resolve(fileURLToPath(import.meta.url))){try{const options=args(process.argv.slice(2)),records=await runSmoke(options);console.log(options.json?JSON.stringify(records):records.map(x=>Object.entries(x).filter(([k])=>["carrier","Result","Changed","Check","Next action"].includes(k)).map(([k,v])=>k+": "+v).join("\n")).join("\n\n"));if(releaseFailed(records))process.exitCode=1;}catch(error){console.error("Result: FAIL\\nChanged: none\\nCheck: "+redact(error.message)+"\\nNext action: inspect carrier seam");process.exitCode=1;}}
