import test from "node:test";
import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { execFile as run } from "node:child_process";
import { promisify } from "node:util";
import { redact as sharedRedact } from "../shared.mjs";
import { CARRIER_REGISTRY, carriersForChangedPaths, childPath, redact, releaseFailed, runSmoke, validateSource } from "./smoke.mjs";
const runFile=promisify(run), root=resolve(import.meta.dirname,"../..");
const has=async name=>runFile("/usr/bin/which",[name]).then(()=>true,()=>false);
test("registry maps supported carriers explicitly",()=>{assert.deepEqual(Object.keys(CARRIER_REGISTRY).sort(),["claude","codex","omp","opencode"]);assert.deepEqual(Object.entries(CARRIER_REGISTRY).filter(([,adapter])=>adapter.required).map(([name])=>name).sort(),["claude","omp"]);for(const adapter of Object.values(CARRIER_REGISTRY)){assert.ok(adapter.source);assert.ok(adapter.owner);assert.equal(typeof adapter.run,"function");}});
test("release fails closed only for required stable seams",()=>{assert.equal(releaseFailed([{carrier:"omp",Result:"N/A"},{carrier:"claude",Result:"PASS"},{carrier:"opencode",Result:"N/A"},{carrier:"codex",Result:"N/A"}]),true);assert.equal(releaseFailed([{carrier:"omp",Result:"PASS"},{carrier:"claude",Result:"PASS"},{carrier:"opencode",Result:"N/A"},{carrier:"codex",Result:"N/A"}]),false);assert.equal(releaseFailed([{carrier:"omp",Result:"PASS"},{carrier:"claude",Result:"PASS"},{carrier:"opencode",Result:"FAIL"}]),true);});
test("real CLIs use authoritative Claude seam and isolated OpenCode",{skip:!(await has("claude"))},async()=>{const carriers=["claude",...(await has("opencode")?["opencode"]:[])];const records=await runSmoke({carriers,source:root,scratch:true});assert.equal(records.find(x=>x.carrier==="claude").Result,"PASS");if(carriers.includes("opencode"))assert.equal(records.find(x=>x.carrier==="opencode").Result,"N/A");assert.equal(existsSync(join(root,".opencode")),false);});
test("exported source seam always enforces canonical repository containment",async()=>{await assert.rejects(validateSource("/definitely/missing"));const expected=await mkdtemp(join(tmpdir(),"loom-expected-")),outside=await mkdtemp(join(tmpdir(),"loom-outside-")),file=join(outside,"file"),link=join(outside,"link"),nested=join(outside,"nested"),ancestor=join(expected,"escaped");await mkdir(nested);await writeFile(file,"x");await symlink(outside,link);await symlink(outside,ancestor);await assert.rejects(validateSource(outside,{expectedRoot:expected}));await assert.rejects(validateSource(file,{expectedRoot:expected}));await assert.rejects(validateSource(link,{expectedRoot:expected}));await assert.rejects(validateSource(join(ancestor,"nested"),{expectedRoot:expected}),/inside expected repository root/);await assert.rejects(runSmoke({carriers:[],source:outside,scratch:true}));await rm(expected,{recursive:true,force:true});await rm(outside,{recursive:true,force:true});});
test("changed paths select all and only affected carriers",()=>{const cases=[
  ["package.json",["omp","claude","opencode"]],
  ["skills/loom/SKILL.md",["omp","claude","opencode","codex"]],
  ["agents/loom-verify-spec.md",["omp","claude"]],
  [".claude-plugin/plugin.json",["omp","claude"]],
  ["opencode-plugin.mjs",["opencode"]],
  [".codex-plugin/plugin.json",["codex"]],
  ["commands/loom.md",["codex"]],
  ["README.md",[]],
];for(const [path,expected] of cases)assert.deepEqual(carriersForChangedPaths([path]),expected,path);for(const [carrier,adapter] of Object.entries(CARRIER_REGISTRY))for(const path of adapter.sourcePaths){const probe=path.endsWith("/")?path+"probe.md":path;assert.ok(carriersForChangedPaths([probe]).includes(carrier),carrier+" "+path)}});
test("redaction preserves JSON and removes credential and path forms",()=>{const input={GITHUB_TOKEN:"github-value",AWS_SECRET_ACCESS_KEY:"aws-value",client_secret:"client-value",private_key:"private-value",ANTHROPIC_API_KEY:"anthropic-value",service_api_key:"service-value",accessToken:"access-value",id_token:"id-value",refresh_token:"refresh-value",PASSWORD:"password-value",Secret:"secret-value",authorization:"authorization-value",nested:{text:'Authorization: Bearer bearer-value Bearer loose-value OPENAI_API_KEY="openai-value" github_token=raw-github AWS_SECRET_ACCESS_KEY: "raw-aws" client_secret=raw-client private_key:"raw-private" access_token=raw-access idToken="raw-id" refresh-token:raw-refresh password=raw-password secret="raw-secret" /Users/name/project'}};const output=redact(JSON.stringify(input)),parsed=JSON.parse(output);for(const key of ["GITHUB_TOKEN","AWS_SECRET_ACCESS_KEY","client_secret","private_key","ANTHROPIC_API_KEY","service_api_key","accessToken","id_token","refresh_token","PASSWORD","Secret","authorization"])assert.equal(parsed[key],"<REDACTED>",key);for(const secret of ["github-value","aws-value","client-value","private-value","anthropic-value","service-value","access-value","id-value","refresh-value","password-value","secret-value","authorization-value","bearer-value","loose-value","openai-value","raw-github","raw-aws","raw-client","raw-private","raw-access","raw-id","raw-refresh","raw-password","raw-secret","/Users/name/project"])assert.equal(output.includes(secret),false,secret);assert.doesNotThrow(()=>JSON.parse(output));});
test("raw text redaction covers quoted and unquoted common secrets",()=>{const probes=[['GITHUB_TOKEN=github-secret','github-secret'],['aws_secret_access_key: "aws-secret"','aws-secret'],["'client_secret'='client-secret'",'client-secret'],['private_key:private-secret','private-secret'],['Authorization: Bearer bearer-secret','bearer-secret'],['SERVICE_API_KEY="api-secret"','api-secret'],['access_token=access-secret','access-secret'],['idToken: id-secret','id-secret'],['refresh-token=refresh-secret','refresh-secret'],['password:password-secret','password-secret'],['secret="generic-secret"','generic-secret']];for(const [input,value] of probes){const output=redact(input);assert.equal(output.includes(value),false,input);assert.match(output,/<REDACTED>/,input)}});
test("child PATH contains only resolved executable directory and fixed system directories",()=>{assert.equal(childPath("/custom/tools/omp"),"/custom/tools:/usr/bin:/bin:/usr/sbin:/sbin");assert.equal(childPath("/usr/bin/omp"),"/usr/bin:/bin:/usr/sbin:/sbin");assert.equal(childPath("/opt/homebrew/bin/omp"),"/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin");assert.equal(childPath("/custom/tools/omp").includes("/opt/homebrew/bin"),false)});
test("generic CI stays deterministic and release docs require live gates",async()=>{const [workflow,smoke,release]=await Promise.all([readFile(join(root,".github/workflows/checks.yml"),"utf8"),readFile(join(root,"scripts/smoke"),"utf8"),readFile(join(root,"RELEASE.md"),"utf8")]);assert.doesNotMatch(workflow,/check-carriers/);assert.doesNotMatch(smoke,/check-carriers/);assert.match(release,/scripts\/check-carriers --all --scratch/);assert.match(release,/scripts\/check-carriers --changed PATH\.\.\./);assert.match(release,/provisioned/i);assert.match(release,/fail-closed|fails closed/i)});
test("real changed-carrier script routes mapped smoke",async()=>{const out=await runFile("scripts/check-carriers",["--changed","opencode-plugin.mjs"],{cwd:root,env:{...process.env,HOME:"/tmp/loom-check-carriers-home"}});const records=JSON.parse(out.stdout.trim());assert.deepEqual(records.map(x=>x.carrier),["opencode"]);assert.equal(records[0].Result,"N/A");assert.equal(existsSync(join(root,".opencode")),false);});
test("Claude missing malformed and disabled fixtures fail authoritatively",{skip:!(await has("claude")),timeout:30000},async()=>{for(const fixture of ["missing","malformed","disabled"]){const records=await runSmoke({carriers:["claude"],source:root,fixture,scratch:true});assert.equal(records[0].Result,"FAIL",fixture);assert.match(records[0]["Next action"],/fixture correctly rejected/);assert.equal(existsSync(join(root,".opencode")),false);}});
test("OpenCode never receives live source on success or failure",async()=>{const seen=[];let fail=false;const deps={access:async()=>{},exec:async(file,args)=>{if(file==="/usr/bin/git")return {stdout:"",stderr:""};if(file==="/usr/bin/which")return {stdout:"/usr/bin/opencode\n",stderr:""};seen.push(args);if(fail)throw Object.assign(Error("forced"),{code:1});return {stdout:"",stderr:""};},rm};for(fail of [false,true]){const records=await runSmoke({carriers:["opencode"],source:root,scratch:true,deps});assert.equal(records[0].Result,"N/A");}assert.equal(seen.some(args=>args.includes(root)),false);assert.equal(existsSync(join(root,".opencode")),false);});

test("OMP malformed fixture requires host rejection or failed discovery",async()=>{const deps={access:async()=>{},exec:async(file,args)=>{if(file==="/usr/bin/git")return {stdout:"",stderr:""};if(file==="/usr/bin/which")return {stdout:"/usr/bin/omp\n",stderr:""};if(args.includes("list"))return {stdout:JSON.stringify([{name:"loom",enabled:true}]),stderr:""};return {stdout:"{}",stderr:""};},rm};const [record]=await runSmoke({carriers:["omp"],source:root,scratch:true,fixture:"malformed",deps});assert.equal(record.Result,"FAIL","accepted malformed metadata must never produce authoritative PASS");assert.match(record.Changed,/malformed package metadata/);assert.match(record.Check,/host must reject or not discover/);assert.equal(record["Next action"],"inspect authoritative state transitions");});

test("OMP normal mode rejects authoritative disabled entry",async()=>{const expected=JSON.parse(await readFile(join(root,"package.json"),"utf8"));const deps={access:async()=>{},exec:async(file,args)=>{if(file==="/usr/bin/git")return {stdout:"",stderr:""};if(file==="/usr/bin/which")return {stdout:"/usr/bin/omp\n",stderr:""};if(args.includes("list"))return {stdout:JSON.stringify([{name:"loom",version:expected.version,enabled:false}]),stderr:""};return {stdout:"{}",stderr:""};},rm};const [record]=await runSmoke({carriers:["omp"],source:root,scratch:true,deps});assert.equal(record.Result,"FAIL");assert.equal(releaseFailed([record]),true)});
test("OMP authoritative PASS requires a present valid matching version",async()=>{const expected=JSON.parse(await readFile(join(root,"package.json"),"utf8")).version;for(const [label,entry] of [["missing",{name:"loom",enabled:true}],["invalid",{name:"loom",version:"not-a-version",enabled:true}],["mismatched",{name:"loom",version:"0.0.0",enabled:true}],["matching",{name:"loom",version:expected,enabled:true}]]){const deps={access:async()=>{},exec:async(file,args)=>{if(file==="/usr/bin/git")return {stdout:"",stderr:""};if(file==="/usr/bin/which")return {stdout:"/usr/bin/omp\n",stderr:""};if(args.includes("list"))return {stdout:JSON.stringify([entry]),stderr:""};return {stdout:"{}",stderr:""};},rm};const [record]=await runSmoke({carriers:["omp"],source:root,scratch:true,deps});assert.equal(record.Result,label==="matching"?"PASS":"FAIL",label);assert.equal(releaseFailed([record]),label!=="matching",label)}});

test("unavailable Codex records concrete resolution evidence without seam claim",async()=>{const deps={access:async()=>{throw Error("absent")},exec:async(file,args)=>file==="/usr/bin/git"?{stdout:"",stderr:""}:{stdout:"",stderr:""},rm};const [record]=await runSmoke({carriers:["codex"],source:root,scratch:true,deps});assert.equal(record.Result,"N/A");assert.match(record.Check,/UNAVAILABLE.*which codex/);assert.match(record.stderr,/codex executable absent.*searched with.*which codex/);assert.match(record["Next action"],/does not prove the carrier seam is absent/);});

test("carrier redaction uses the comprehensive shared persistence boundary",()=>{assert.equal(redact,sharedRedact);const input='Authorization: Basic YmFk\nx-api-key: key\nCookie: sid=cookie\nSet-Cookie: auth=set\napiKey=plain client_secret:"quoted" https://user:pass@example.com /opt/private/file ../secret/file C:\\Users\\me\\file relative\\windows\\file';const out=redact(input);for(const leak of ["YmFk","sid=cookie","auth=set","plain","quoted","user:pass","/opt/private","../secret","C:\\Users","relative\\windows"])assert.equal(out.includes(leak),false,leak)});
test("carrier OMP closure excludes invoking PATH and includes validated bun only",async()=>{const seen=[];const expected=JSON.parse(await readFile(join(root,"package.json"),"utf8"));const deps={access:async path=>{if(!["/custom/omp","/runtime/bin/bun"].includes(path))throw Error("unexpected "+path)},exec:async(file,args,options)=>{if(file==="/usr/bin/git")return{stdout:"",stderr:""};if(file==="/usr/bin/which")return{stdout:args[0]==="omp"?"/custom/omp\n":"/runtime/bin/bun\n",stderr:""};if(args[0]==="--version"){seen.push(options.env.PATH);if(seen.length===1)throw Object.assign(Error("env: bun: No such file"),{stderr:"env: bun: No such file"});return{stdout:"omp/17.2.7",stderr:""}}assert.equal(options.env.PATH,"/custom:/runtime/bin:/usr/bin:/bin:/usr/sbin:/sbin");if(args.includes("list"))return{stdout:JSON.stringify([{name:"loom",version:expected.version,enabled:true}]),stderr:""};return{stdout:"{}",stderr:""}},rm};const [record]=await runSmoke({carriers:["omp"],source:root,scratch:true,deps});assert.equal(record.Result,"PASS");assert.deepEqual(seen,["/custom:/usr/bin:/bin:/usr/sbin:/sbin","/custom:/runtime/bin:/usr/bin:/bin:/usr/sbin:/sbin"])});
