"use strict";
const {createHash}=require("node:crypto");
const {execFileSync}=require("node:child_process");
const {lstatSync,readFileSync,readlinkSync,realpathSync}=require("node:fs");
const {relative,resolve,sep}=require("node:path");
const REPOSITORY_KEY=/^(?:\.|[a-z0-9][a-z0-9._-]*(?:\/[a-z0-9][a-z0-9._-]*)*)$/;
const REPOSITORY_FIELDS=new Set(["key","head","diffDigest"]),BOUNDARY_FIELDS=new Set(["ticketDigest","repositories","digest"]);
function bytes(value){return Buffer.isBuffer(value)?value:Buffer.from(String(value))}
function frame(tag,value){const t=bytes(tag),v=bytes(value),a=Buffer.alloc(16);a.writeBigUInt64BE(BigInt(t.length),0);a.writeBigUInt64BE(BigInt(v.length),8);return Buffer.concat([a,t,v])}
function hashFrames(frames){const hash=createHash("sha256");for(const [tag,value] of frames)hash.update(frame(tag,value));return hash.digest("hex")}
function ticketSnapshot(ticket){const frames=[["id",ticket.id],["storyId",ticket.storyId],["blockedBy.count",String(ticket.blockedBy.length)]];ticket.blockedBy.forEach(x=>frames.push(["blockedBy",x]));const keys=ticket.repositoryKeys||["."];frames.push(["repositoryKeys.count",String(keys.length)]);keys.forEach(x=>frames.push(["repositoryKey",x]));for(const name of ticket.sectionOrder||Object.keys(ticket.sections))if(name!=="Verify")frames.push([`section:${name}`,ticket.sections[name]]);return frames}
function ticketDigest(ticket){return hashFrames(ticketSnapshot(ticket))}
function exactFields(value,fields){return value&&typeof value==="object"&&!Array.isArray(value)&&Object.keys(value).length===fields.size&&Object.keys(value).every(x=>fields.has(x))}
function normalizeRepositories(repositories){if(!Array.isArray(repositories)||!repositories.length)throw new TypeError("repositories required");const seen=new Set();return repositories.map(x=>{if(!exactFields(x,REPOSITORY_FIELDS)||!REPOSITORY_KEY.test(x.key)||seen.has(x.key)||!/^[a-f0-9]{40,64}$/i.test(x.head)||!/^[a-f0-9]{64}$/i.test(x.diffDigest))throw new TypeError("repository invalid or duplicated");seen.add(x.key);return{key:x.key,head:x.head.toLowerCase(),diffDigest:x.diffDigest.toLowerCase()}}).sort((a,b)=>Buffer.compare(Buffer.from(a.key),Buffer.from(b.key)))}
function computeBoundary(ticket,repositories){if(!ticket||typeof ticket!=="object"||!Array.isArray(ticket.blockedBy)||!ticket.sections||typeof ticket.sections!=="object")throw new TypeError("ticket invalid");const normalized=normalizeRepositories(repositories),td=ticketDigest(ticket),frames=[["ticket",td],["repositories.count",String(normalized.length)]];for(const repo of normalized)frames.push(["repository.key",repo.key],["repository.head",repo.head],["repository.diff",repo.diffDigest]);return{ticketDigest:td,repositories:normalized,digest:hashFrames(frames)}}
function parseBoundary(value){const b=typeof value==="string"?JSON.parse(value):value;if(!exactFields(b,BOUNDARY_FIELDS)||!/^[a-f0-9]{64}$/.test(b.ticketDigest)||!/^[a-f0-9]{64}$/.test(b.digest))throw new TypeError("boundary invalid");const repositories=normalizeRepositories(b.repositories),frames=[["ticket",b.ticketDigest],["repositories.count",String(repositories.length)]];for(const repo of repositories)frames.push(["repository.key",repo.key],["repository.head",repo.head],["repository.diff",repo.diffDigest]);const digest=hashFrames(frames);if(digest!==b.digest)throw new TypeError("boundary digest mismatch");return{ticketDigest:b.ticketDigest,repositories,digest}}
const renderBoundary=value=>JSON.stringify(parseBoundary(value));
function gitBuffer(repo,args){return execFileSync("git",["-C",repo,...args],{encoding:"buffer",stdio:["ignore","pipe","pipe"]})}
function splitZero(buffer){const out=[];let start=0;for(let i=0;i<buffer.length;i++)if(buffer[i]===0){if(i>start)out.push(buffer.subarray(start,i));start=i+1}return out}
function untrackedFrames(paths,read){const sorted=[...paths].sort(Buffer.compare),frames=[["untracked.count",String(sorted.length)]];for(const path of sorted){const raw=read(path),entry=Buffer.isBuffer(raw)?{type:"regular",content:raw}:raw;frames.push(["untracked.path",path],["untracked.type",entry.type],["untracked.content",entry.content])}return frames}
function readUntracked(root,path){const full=Buffer.concat([root,path]),stat=lstatSync(full);if(stat.isFile())return{type:"regular",content:readFileSync(full)};if(stat.isSymbolicLink())return{type:"symlink",content:readlinkSync(full,{encoding:"buffer"})};throw new TypeError("unsupported untracked file type")}
function repositoryDiffDigest(repositoryPath,exclusions=[]){const pathspecs=exclusions.map(x=>`:!/${x}`),frames=[];frames.push(["staged",gitBuffer(repositoryPath,["diff","--cached","--binary","--",".",...pathspecs])]);frames.push(["unstaged",gitBuffer(repositoryPath,["diff","--binary","--",".",...pathspecs])]);const paths=splitZero(gitBuffer(repositoryPath,["ls-files","--others","--exclude-standard","-z","--",".",...pathspecs])),root=Buffer.from(resolve(repositoryPath)+sep);frames.push(...untrackedFrames(paths,path=>readUntracked(root,path)));return hashFrames(frames)}
function contained(root,path){const rel=relative(root,path);return rel===""||rel!==".."&&!rel.startsWith(`..${sep}`)}
function repositoryPath(root,key){if(!REPOSITORY_KEY.test(key))throw new TypeError("repository key invalid");const lexicalRoot=resolve(root),realRoot=realpathSync(lexicalRoot),repo=resolve(realRoot,key),stat=lstatSync(repo);if(!stat.isDirectory()||realpathSync(repo)!==repo||!contained(realRoot,repo))throw new TypeError("repository path must be a contained real directory");return repo}
function observeRepositories(root,keys,excludedFile){return keys.map(key=>{const repo=repositoryPath(root,key);let exclude=[];if(excludedFile){const raw=resolve(excludedFile),file=resolve(realpathSync(root),relative(resolve(root),raw)),rel=relative(repo,file);if(contained(repo,file)){try{const stat=lstatSync(file);if(!stat.isFile()||realpathSync(file)!==file)throw new TypeError("excluded Ticket must be a contained real file")}catch(error){if(error?.code!=="ENOENT")throw error}exclude=[rel.split(sep).join("/")]}}return{key,head:gitBuffer(repo,["rev-parse","HEAD"]).toString("ascii").trim(),diffDigest:repositoryDiffDigest(repo,exclude)}})}
function computeCurrentBoundary(root,ticket){return computeBoundary(ticket,observeRepositories(root,ticket.repositoryKeys||["."],ticket.filePath))}
module.exports={computeBoundary,computeCurrentBoundary,frame,hashFrames,normalizeRepositories,observeRepositories,parseBoundary,renderBoundary,repositoryDiffDigest,ticketDigest,ticketSnapshot,untrackedFrames};
