"use strict";
function stop(reason){return{valid:false,reason}}
function exact(value,keys,name){if(value===null||typeof value!=="object"||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)return`${name} must be an exact plain object`;const actual=Reflect.ownKeys(value);if(actual.length!==keys.length||keys.some(k=>!Object.hasOwn(value,k))||actual.some(k=>typeof k!=="string"||!keys.includes(k)))return`${name} must have exactly: ${keys.join(", ")}`;return null}
function strings(value,name,{empty=true}={}){if(!Array.isArray(value)||(!empty&&!value.length)||value.some(x=>typeof x!=="string"||!x.trim())||new Set(value).size!==value.length)return`${name} must be ${empty?"an":"a nonempty"} unique string array`;return null}
function validateContextKnowledge(input){let reason=exact(input,["registeredRepositories","entries"],"CONTEXT knowledge");if(reason)return stop(reason);if((reason=strings(input.registeredRepositories,"registeredRepositories")))return stop(reason);if(!Array.isArray(input.entries))return stop("entries must be an array");const contracts=new Set();for(const[index,entry]of input.entries.entries()){if((reason=exact(entry,["name","kind","scope"],`entries[${index}]`)))return stop(reason);if(typeof entry.name!=="string"||!entry.name.trim()||!["Term","Contract"].includes(entry.kind)||(reason=strings(entry.scope,`entries[${index}] scope`)))return stop(reason||"invalid CONTEXT entry");if(entry.kind==="Contract"&&!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(entry.name))return stop("Contract names must be lowercase kebab-case");if(entry.scope.some(name=>!input.registeredRepositories.includes(name)))return stop("CONTEXT scope contains an unregistered repository name");if(entry.kind==="Contract"){if(contracts.has(entry.name))return stop("Contract names must be unique");contracts.add(entry.name)}}return{valid:true,contracts:[...contracts].sort()}}
function validateAdrScope(input){let reason=exact(input,["scope","registeredRepositories","contractNames"],"ADR scope");if(reason)return stop(reason);if((reason=strings(input.registeredRepositories,"registeredRepositories"))||(reason=strings(input.contractNames,"contractNames")))return stop(reason);if(input.scope==="workspace-wide")return{valid:true,scope:{workspaceWide:true,repositories:[],contracts:[]}};if((reason=exact(input.scope,["repositories","contracts"],"ADR scoped names")))return stop(reason);if((reason=strings(input.scope.repositories,"ADR repositories"))||(reason=strings(input.scope.contracts,"ADR contracts")))return stop(reason);if(!input.scope.repositories.length&&!input.scope.contracts.length)return stop("ADR scope must name a repository, Contract, or workspace-wide");if(input.scope.repositories.some(name=>!input.registeredRepositories.includes(name)))return stop("ADR scope contains an unregistered repository name");if(input.scope.contracts.some(name=>!input.contractNames.includes(name)))return stop("ADR scope contains an unknown Contract name");return{valid:true,scope:{workspaceWide:false,repositories:[...input.scope.repositories],contracts:[...input.scope.contracts]}}}
function planAdrEvolution(input){const reason=exact(input,["applied","compatible","clarification"],"ADR evolution");if(reason)return stop(reason);if([input.applied,input.compatible,input.clarification].some(x=>typeof x!=="boolean"))return stop("ADR evolution flags must be booleans");if(input.clarification)return{valid:true,action:"AMEND_NOTE"};if(!input.applied)return{valid:true,action:"AMEND"};return{valid:true,action:input.compatible?"AMEND":"SUPERSEDE"}}
function planKnowledgeWrite(input){const reason=exact(input,["actor","changes"],"knowledge write");if(reason)return stop(reason);if(!["coordinator","worker"].includes(input.actor)||!Array.isArray(input.changes))return stop("invalid knowledge writer or changes");if(input.changes.some(x=>!["ADR","CONTEXT"].includes(x)))return stop("shared knowledge changes must be ADR or CONTEXT");return input.actor==="coordinator"?{valid:true,action:"WRITE",changes:[...new Set(input.changes)]}:{valid:true,action:"DECISION_NEEDED",changes:[]}}
module.exports={planAdrEvolution,planKnowledgeWrite,validateAdrScope,validateContextKnowledge};
