"use strict";
const { canonicalCopy, exactSchemaMismatches, hashValue, trimmedString } = require("./planner-utils.cjs");
const { validateLaneEvidenceReceipt } = require("./lane-evidence.cjs");
const REQUEST_KEYS=["operation","targets","scope"], EVIDENCE_KEYS=["observedAt","request","facts"], CONFIRM_KEYS=["requestDigest","stateFingerprint","confirmedAt","expiresAt","nonce","provenance"], AUTH_KEYS=["request","requestDigest","stateFingerprint","confirmedAt","expiresAt","nonce","provenance"];
const COMMON_FACT_KEYS=["identity","privacy","git","laneReceipt","operation"];
const OPERATION_FACT_KEYS={
  migrate:["storyPath","beforeDigest","afterDigest","workspaceIdentity"],
  "finish-owner-integration":["inventoryDigest","ownerId","files"],
  "finish-service-commit":["inventoryDigest","repository","tree"],
  publish:["repository","remote","branch","commit","refspec"],
  "tend-reconcile":["storyId","writerId","reconciliationDigest"],
  "tend-archive":["storyId","archiveTarget","archiveDigest"],
  cleanup:["repository","repositoryId","nativeId","selector","branch","head","mergeCommit","kind","clean","inactive"]
};
const mintedAuthorities=new WeakSet(), adapterCapabilities=new WeakSet();
const deny=(reason)=>({decision:"DENY",reason});
const iso=(value)=>typeof value==="string"&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value)&&new Date(value).toISOString()===value;
function canonical(value){if(value===null||["string","boolean"].includes(typeof value))return value;if(typeof value==="number"&&Number.isFinite(value))return value;if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==="object"&&Object.getPrototypeOf(value)===Object.prototype){const out={};for(const key of Object.keys(value).sort())out[key]=canonical(value[key]);return out;}throw new Error("value is not canonical JSON");}
function validateMutationRequest(value){const errors=exactSchemaMismatches(value,REQUEST_KEYS,"MutationRequest");if(!trimmedString(value?.operation)||!OPERATION_FACT_KEYS[value?.operation])errors.push("MutationRequest operation is unsupported");if(!Array.isArray(value?.targets)||!value.targets.length||value.targets.some((x)=>!trimmedString(x))||new Set(value?.targets||[]).size!==value?.targets?.length)errors.push("MutationRequest targets must be unique nonempty strings");try{canonical(value?.scope);}catch{errors.push("MutationRequest scope must be canonical JSON");}return errors;}
function nonempty(value){return trimmedString(value);}
function validateLiveEvidence(value,{now=value?.observedAt,maxAgeMs=300000}={}){const errors=exactSchemaMismatches(value,EVIDENCE_KEYS,"LiveEvidence");errors.push(...validateMutationRequest(value?.request));if(!iso(value?.observedAt))errors.push("LiveEvidence observedAt must be exact ISO UTC");else if(!iso(now)||!Number.isFinite(maxAgeMs)||maxAgeMs<0||Date.parse(value.observedAt)>Date.parse(now)||Date.parse(now)-Date.parse(value.observedAt)>maxAgeMs)errors.push("LiveEvidence is future, stale, or freshness inputs are invalid");const facts=value?.facts;errors.push(...exactSchemaMismatches(facts,COMMON_FACT_KEYS,"LiveEvidence facts"));errors.push(...exactSchemaMismatches(facts?.identity,["workspace","storyId","ownerId"],"LiveEvidence identity"));for(const key of ["workspace","storyId","ownerId"])if(!nonempty(facts?.identity?.[key]))errors.push(`LiveEvidence identity ${key} must be nonempty`);
errors.push(...exactSchemaMismatches(facts?.privacy,["violations"],"LiveEvidence privacy"));if(!Array.isArray(facts?.privacy?.violations)||facts.privacy.violations.length)errors.push("LiveEvidence privacy violations must be an empty array");
errors.push(...exactSchemaMismatches(facts?.git,["repository","repositoryId","branch","head","tree","status","worktreePath"],"LiveEvidence git"));for(const key of ["repository","repositoryId","branch","head","tree","worktreePath"])if(!nonempty(facts?.git?.[key]))errors.push(`LiveEvidence git ${key} must be nonempty`);if(typeof facts?.git?.status!=="string")errors.push("LiveEvidence git status must be a string");
const opKeys=OPERATION_FACT_KEYS[value?.request?.operation]||[];errors.push(...exactSchemaMismatches(facts?.operation,opKeys,`${value?.request?.operation||"unknown"} evidence`));for(const key of opKeys.filter((x)=>!["clean","inactive","files","workspaceIdentity"].includes(x)))if(!nonempty(facts?.operation?.[key]))errors.push(`${value?.request?.operation} evidence ${key} must be nonempty`);if(value?.request?.operation==="cleanup"&&(facts?.operation?.clean!==true||facts?.operation?.inactive!==true))errors.push("cleanup evidence must derive clean and inactive true");
const lane=validateLaneEvidenceReceipt(facts?.laneReceipt,{now,maxAgeMs});if(lane?.action==="STOP")errors.push(`LiveEvidence laneReceipt: ${lane.reason}`);
if(facts?.identity?.storyId!==value?.request?.scope?.storyId)errors.push("LiveEvidence identity storyId differs from request");
if(lane?.action!=="STOP"){if(lane.storyId!==value.request.scope.storyId)errors.push("LaneEvidenceReceipt storyId differs from request");const gitLane=lane.gitState.find((x)=>x.repositoryId===facts.git.repositoryId),nativeLane=lane.nativeRuntime.find((x)=>x.repositoryId===facts.git.repositoryId);if(!gitLane||!nativeLane)errors.push("operation repository is absent from lane receipt");else{for(const key of ["repository","repositoryId","branch","head","worktreePath"])if(gitLane[key]!==facts.git[key])errors.push(`LiveEvidence Git ${key} differs from lane receipt`);if(nativeLane.selector!==nativeLane.laneId)errors.push("native selector differs from lane identity");if(value.request.operation==="cleanup"){const op=facts.operation;if(op.repository!==gitLane.repository||op.repositoryId!==gitLane.repositoryId||op.nativeId!==nativeLane.laneId||op.selector!==nativeLane.selector||op.branch!==gitLane.branch||op.head!==gitLane.head)errors.push("cleanup operation target differs from exact lane/Git mapping");if(op.clean!==(gitLane.status===""&&gitLane.diffSummary==="clean")||op.clean!==(facts.git.status===""))errors.push("cleanup clean state contradicts Git status");if(op.inactive!==(nativeLane.status==="inactive"))errors.push("cleanup inactive state contradicts native status");}if(value.request.operation==="publish"&&(facts.operation.repository!==gitLane.repository||facts.operation.branch!==gitLane.branch||facts.operation.commit!==gitLane.head))errors.push("publish target differs from exact lane/Git mapping");}}
try{canonical(facts);}catch{errors.push("LiveEvidence facts must be canonical JSON");}
return errors;}
const digestMutationRequest=(value)=>hashValue(canonical(value));
const digestLiveEvidence=(value)=>hashValue(canonical(value));
function stableLiveState(value){const lane=value?.facts?.laneReceipt;const stableLane=lane&&typeof lane==="object"?Object.fromEntries(Object.entries(lane).filter(([key])=>!["observedAt","digest"].includes(key))):lane;return canonical({request:value?.request,facts:{...value?.facts,laneReceipt:stableLane}});}
const fingerprintLiveState=(value)=>hashValue(stableLiveState(value));
function mintMutationAuthority(request,evidence,capability,{now=new Date().toISOString(),maxAgeMs=300000}={}){const errors=[...validateMutationRequest(request),...validateLiveEvidence(evidence,{now,maxAgeMs})];if(!capability||!adapterCapabilities.has(capability)||exactSchemaMismatches(capability,CONFIRM_KEYS,"AttendedCapability").length)errors.push("attended adapter capability is absent");if(JSON.stringify(canonical(request))!==JSON.stringify(canonical(evidence?.request)))errors.push("confirmation evidence request differs");if(capability?.requestDigest!==digestMutationRequest(request))errors.push("confirmation request digest differs");if(capability?.stateFingerprint!==fingerprintLiveState(evidence))errors.push("confirmation state fingerprint differs");const t=Date.parse(now);if(!iso(now)||Date.parse(capability?.confirmedAt)>t||Date.parse(capability?.expiresAt)<=t)errors.push("confirmation is future or expired");if(errors.length)return deny(errors.join("; "));const authority=canonicalCopy({request:canonical(request),...capability});mintedAuthorities.add(authority);return authority;}
function createAttendedMutationAdapter(confirmAttended,buildAction){if(typeof confirmAttended!=="function"||typeof buildAction!=="function")throw new TypeError("attended adapter requires host confirmation and fixed action callbacks");return async function withAttendedMutation({request,collectEvidence,now=new Date().toISOString(),maxAgeMs=300000}){if(typeof collectEvidence!=="function")return deny("attended mutation requires an evidence closure");const evidence=await collectEvidence();const prompt={request:canonicalCopy(request),requestDigest:digestMutationRequest(request),stateFingerprint:fingerprintLiveState(evidence)};const confirmation=await confirmAttended(prompt);if(confirmation?.confirmed!==true)return deny("host attended confirmation denied or unavailable");const raw={requestDigest:prompt.requestDigest,stateFingerprint:prompt.stateFingerprint,confirmedAt:confirmation.confirmedAt,expiresAt:confirmation.expiresAt,nonce:confirmation.nonce,provenance:confirmation.provenance};const errors=exactSchemaMismatches(raw,CONFIRM_KEYS,"AttendedCapability");for(const key of ["confirmedAt","expiresAt"])if(!iso(raw[key]))errors.push(`AttendedCapability ${key} must be exact ISO UTC`);for(const key of ["requestDigest","stateFingerprint"])if(!/^[a-f0-9]{64}$/.test(raw[key]||""))errors.push(`AttendedCapability ${key} must be SHA-256`);if(!nonempty(raw.nonce)||!nonempty(raw.provenance))errors.push("attended capability nonce and provenance must be nonempty");if(errors.length)return deny(errors.join("; "));const capability=canonicalCopy(raw);adapterCapabilities.add(capability);const authority=mintMutationAuthority(request,evidence,capability,{now,maxAgeMs});if(authority.decision==="DENY")return authority;const refreshed=await collectEvidence();const decision=guardMutation(request,authority,refreshed,{now,maxAgeMs});return decision==="ALLOW"?buildAction({request:canonicalCopy(request),evidence:refreshed,authority}):decision;};}
function guardMutation(request,authority,evidence,{now=new Date().toISOString(),maxAgeMs=300000}={}){const errors=[...validateMutationRequest(request),...validateLiveEvidence(evidence,{now,maxAgeMs})];if(errors.length)return deny(errors.join("; "));if(!authority||exactSchemaMismatches(authority,AUTH_KEYS,"MutationAuthority").length||!mintedAuthorities.has(authority))return deny("explicit process-local mutation authority is absent");if(JSON.stringify(canonical(request))!==JSON.stringify(canonical(authority.request))||authority.requestDigest!==digestMutationRequest(request))return deny("authority request is mismatched or over-broad");if(JSON.stringify(canonical(request))!==JSON.stringify(canonical(evidence.request)))return deny("live evidence request differs");if(authority.stateFingerprint!==fingerprintLiveState(evidence))return deny("authority is stale for substantive current state");if(!iso(now)||Date.parse(authority.confirmedAt)>Date.parse(now)||Date.parse(authority.expiresAt)<=Date.parse(now))return deny("authority is future or expired");return "ALLOW";}
module.exports={createAttendedMutationAdapter,digestLiveEvidence,digestMutationRequest,fingerprintLiveState,guardMutation,mintMutationAuthority,validateLiveEvidence,validateMutationRequest};
