"use strict";

const { canonicalCopy, exactSchemaMismatches, fail, hashString, hashValue, trimmedString } = require("./planner-utils.cjs");
function publicationDigest(value) { return hashValue(value); }
function stopAwaiting(reason) { return { action: "STOP", lifecycle: "awaiting-review", mutation: false, reason }; }

function classifyTendIntent(value) {
  if (typeof value !== "string") fail("Tend intent must be a string");
  return value === "/loom tend" ? { action: "TEND", mutation: false } : { action: "NOOP", mutation: false };
}

function normalizedRelativePath(value) {
  if (!trimmedString(value) || value !== value.trim() || value.startsWith("/") || value.includes("\\") || value.startsWith("~") || /^[a-z]:/i.test(value)) return false;
  const parts = value.split("/"); return !parts.some((part) => !part || part === "." || part === "..");
}
function validObservedAt(value) { return typeof value === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(value) && !Number.isNaN(Date.parse(value)); }
function validPublicRef(value) { try { const url = new URL(value); return ["https:", "http:"].includes(url.protocol) && trimmedString(url.hostname) && !/[\\\s]/.test(value); } catch { return /^urn:review:[A-Za-z0-9._~:/?#@!$&'()*+,;=%-]+$/.test(value); } }
function projectionLeak(value) {
  const patterns = [/(?:^|[\s"'=:(])\/(?:[^\s]+\/)*[^\s]*/, /(?:^|[\s"'=:(])~[\\/]/, /(?:^|[\s"'=:(])[a-z]:[\\/]/i, /\\\\[^\\\s]+\\[^\s]+/, /\b(?:task|terminal|session)_[a-z0-9_-]+\b/i, /\b(?:orca\s+worktree|omp\s+(?:session|worker|terminal)|runtime\s+(?:session|terminal)|pushAttempts|reviewAttempts|ghAvailable|remoteSupported|stop-on-first-failure)\b/i];
  return patterns.some((pattern) => pattern.test(value));
}
function laneIdentity(lane) { return Object.fromEntries(["repository", "repositoryId", "nativeId", "branch", "base", "commit", "tree", "publicationRef", "host", "remote"].map((key) => [key, lane[key]])); }
function validatePublishedLanes(value, mismatches) {
  const keys = ["repository", "repositoryId", "nativeId", "branch", "base", "commit", "tree", "publicationRef", "host", "remote"];
  if (!Array.isArray(value) || value.length === 0) { mismatches.push("publishedLanes must be nonempty"); return; }
  value.forEach((lane,index)=>{const name=`publishedLanes[${index}]`;const shape=exactSchemaMismatches(lane,keys,name);mismatches.push(...shape);if(shape.length)return;for(const key of keys)if(!trimmedString(lane[key]))mismatches.push(`${name} ${key} must be nonempty`);if(!validPublicRef(lane.publicationRef))mismatches.push(`${name} publicationRef is invalid`);});
  for(const field of ["repository","repositoryId","nativeId","publicationRef"])if(new Set(value.map((lane)=>lane?.[field])).size!==value.length)mismatches.push(`published lane ${field}s must be unique`);
}
function validateMergeProofs(proofs, lanes, mismatches) {
  if (!Array.isArray(proofs) || proofs.length !== lanes.length) { mismatches.push("exactly one merge proof per published lane is required"); return; }
  const seen=new Set();
  proofs.forEach((proof,index)=>{const name=`mergeProofs[${index}]`;if(proof===null||typeof proof!=="object"||Array.isArray(proof)){mismatches.push(`${name} must be an exact object`);return;}const host=proof.type==="host-merged";const local=proof.type==="accepted-local-merge";if(!host&&!local){mismatches.push(`${name} has unsupported type`);return;}const keys=host?["type","repository","repositoryId","nativeId","publicationRef","headBranch","headCommit","targetBranch","state","mergeCommit","observedAt"]:["type","repository","repositoryId","nativeId","branch","headCommit","targetBranch","mergeCommit","ancestryObserved","acceptedByUser","observedAt"];const shape=exactSchemaMismatches(proof,keys,name);mismatches.push(...shape);if(shape.length)return;const lane=lanes.find((candidate)=>candidate.repositoryId===proof.repositoryId);if(!lane){mismatches.push(`${name} has no published lane`);return;}const identityKey=`${proof.repositoryId}\0${proof.nativeId}`;if(seen.has(identityKey))mismatches.push(`${name} duplicates lane proof`);seen.add(identityKey);for(const key of ["repository","repositoryId","nativeId","mergeCommit"])if(!trimmedString(proof[key]))mismatches.push(`${name} ${key} must be nonempty`);if(!validObservedAt(proof.observedAt))mismatches.push(`${name} observedAt must be a valid UTC timestamp`);if(proof.repository!==lane.repository||proof.nativeId!==lane.nativeId)mismatches.push(`${name} identity differs from published lane`);if(host&&(proof.publicationRef!==lane.publicationRef||proof.headBranch!==lane.branch||proof.headCommit!==lane.commit||proof.targetBranch!==lane.base||proof.state!=="merged"))mismatches.push(`${name} host merge fields differ from published lane or merged state`);if(local&&(proof.branch!==lane.branch||proof.headCommit!==lane.commit||proof.targetBranch!==lane.base||proof.ancestryObserved!==true||proof.acceptedByUser!==true))mismatches.push(`${name} local merge fields or explicit acceptance are invalid`);});
}

function planTendReconciliation(input) {
  const shape=exactSchemaMismatches(input,["story","owner","publishedLanes","mergeProofs","writer","deltas","conflicts","adrCollisions"],"Tend reconciliation inventory");if(shape.length)return stopAwaiting(shape.join("; "));
  const mismatches=[...exactSchemaMismatches(input.story,["id","lifecycle"],"reconciliation story"),...exactSchemaMismatches(input.owner,["ownerId","versioning","targetBranch","storyCommit","storyTree","mainCommit"],"reconciliation owner"),...exactSchemaMismatches(input.writer,["writerId","exclusive"],"reconciliation writer"),...exactSchemaMismatches(input.conflicts,["textual","semantic"],"reconciliation conflicts")];
  if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(input.story?.id||"")||input.story?.lifecycle!=="awaiting-review")mismatches.push("reconciliation requires an awaiting-review story");
  if(input.owner?.versioning!=="git"||input.owner?.targetBranch!=="main")mismatches.push("semantic reconciliation is a Git owner-main integration");
  for(const key of ["ownerId","storyCommit","storyTree","mainCommit"])if(!trimmedString(input.owner?.[key]))mismatches.push(`reconciliation owner ${key} must be nonempty`);
  if(!trimmedString(input.writer?.writerId)||input.writer?.exclusive!==true)mismatches.push("Tend requires one exclusive owner-main writer");
  if(typeof input.conflicts?.textual!=="boolean"||typeof input.conflicts?.semantic!=="boolean")mismatches.push("reconciliation conflict flags must be boolean");
  validatePublishedLanes(input.publishedLanes,mismatches);validateMergeProofs(input.mergeProofs,Array.isArray(input.publishedLanes)?input.publishedLanes:[],mismatches);
  if(!Array.isArray(input.deltas)||input.deltas.length===0)mismatches.push("semantic reconciliation deltas must be nonempty");
  for(const[index,d]of(Array.isArray(input.deltas)?input.deltas:[]).entries()){const name=`deltas[${index}]`;const ds=exactSchemaMismatches(d,["kind","path","beforeDigest","afterDigest","summary"],name);mismatches.push(...ds);if(ds.length)continue;if(!["CONTEXT","ADR","archive"].includes(d.kind)||!normalizedRelativePath(d.path)||!trimmedString(d.summary)||![d.beforeDigest,d.afterDigest].every((x)=>x===null||/^[a-f0-9]{64}$/.test(x)))mismatches.push(`${name} is invalid`);}
  if(!Array.isArray(input.adrCollisions))mismatches.push("adrCollisions must be an array");
  for(const[index,c]of(Array.isArray(input.adrCollisions)?input.adrCollisions:[]).entries()){const name=`adrCollisions[${index}]`;const cs=exactSchemaMismatches(c,["incomingPath","existingPath","renumberedPath","updatedPointers"],name);mismatches.push(...cs);if(cs.length)continue;if(![c.incomingPath,c.existingPath,c.renumberedPath].every(normalizedRelativePath)||c.incomingPath===c.renumberedPath||!/^docs\/adr\/\d{4}-.+\.md$/.test(c.renumberedPath)||!Array.isArray(c.updatedPointers)||!c.updatedPointers.length||c.updatedPointers.some((x)=>!normalizedRelativePath(x)))mismatches.push(`${name} renumbering/pointers are invalid`);}
  if(mismatches.length)return stopAwaiting(mismatches.join("; "));if(input.conflicts.textual||input.conflicts.semantic)return{action:"GRILL_STOP",lifecycle:"awaiting-review",mutation:false,reason:"textual or semantic owner-main conflict requires Grill"};
  const inventory=canonicalCopy(input);inventory.publishedLanes.sort((a,b)=>a.repository.localeCompare(b.repository));inventory.mergeProofs.sort((a,b)=>a.repository.localeCompare(b.repository));inventory.deltas.sort((a,b)=>a.path.localeCompare(b.path));inventory.adrCollisions.sort((a,b)=>a.incomingPath.localeCompare(b.incomingPath));return{action:"RECONCILIATION_PREVIEW",lifecycle:"awaiting-review",mutation:false,inventory,digest:publicationDigest(inventory),confirmationRequired:true,mergeMethod:"ordinary-merge",prohibitedEffects:["rebase","stash","reset","force","push"]};
}
function planTendReconciliationResult(input){
  const shape=exactSchemaMismatches(input,["inventory","confirmedDigest","currentInventory","integration"],"Tend reconciliation result");if(shape.length)return stopAwaiting(shape.join("; "));const preview=planTendReconciliation(input.inventory),current=planTendReconciliation(input.currentInventory);if(preview.action!=="RECONCILIATION_PREVIEW"||current.action!=="RECONCILIATION_PREVIEW"||preview.digest!==input.confirmedDigest||current.digest!==input.confirmedDigest)return stopAwaiting("reconciliation inventory or confirmation is stale");
  const is=exactSchemaMismatches(input.integration,["method","status","commit","tree","writerId","appliedDeltas"],"reconciliation integration");if(is.length)return stopAwaiting(is.join("; "));if(input.integration.method!=="ordinary-merge"||input.integration.writerId!==preview.inventory.writer.writerId||!["integrated","conflict","failed"].includes(input.integration.status))return stopAwaiting("owner-main integration evidence is invalid");if(input.integration.status!=="integrated")return{action:input.integration.status==="conflict"?"GRILL_STOP":"STOP",lifecycle:"awaiting-review",mutation:false,reason:"owner-main integration stopped without rollback"};if(!trimmedString(input.integration.commit)||!trimmedString(input.integration.tree)||JSON.stringify(input.integration.appliedDeltas)!==JSON.stringify(preview.inventory.deltas))return stopAwaiting("integrated owner-main tree or semantic deltas differ from confirmation");
  const serviceMerges=preview.inventory.mergeProofs.map((proof)=>({repository:proof.repository,repositoryId:proof.repositoryId,mergeCommit:proof.mergeCommit}));return{action:"RECONCILED",lifecycle:"awaiting-review",receipt:{storyId:preview.inventory.story.id,reconciliationDigest:preview.digest,storyCommit:preview.inventory.owner.storyCommit,storyTree:preview.inventory.owner.storyTree,ownerCommit:input.integration.commit,ownerTree:input.integration.tree,serviceMerges,deltas:preview.inventory.deltas,adrCollisions:preview.inventory.adrCollisions}};
}

function archiveArtifactDigest(content){return hashString(content);}
function artifactCategory(path,target){const rest=path.slice(target.length+1);if(rest==="STORY.md")return"STORY";if(rest==="PRD.md")return"PRD";if(/^issues\/[^/]+\.md$/.test(rest))return"issues";if(rest==="MANIFEST.json")return"manifest";if(rest==="CONTEXT.md")return"CONTEXT";if(/^adr\/[^/]+\.md$/i.test(rest))return"ADR";return null;}
function validateReconciliationReceipt(receipt,storyId,lanes,proofs,mismatches){
  const keys=["storyId","reconciliationDigest","storyCommit","storyTree","ownerCommit","ownerTree","serviceMerges","deltas","adrCollisions"];
  const rs=exactSchemaMismatches(receipt,keys,"archive reconciliation receipt");mismatches.push(...rs);if(rs.length)return;
  if(receipt.storyId!==storyId||!["reconciliationDigest","storyCommit","storyTree","ownerCommit","ownerTree"].every((key)=>trimmedString(receipt[key])))mismatches.push("archive reconciliation receipt identity is invalid");
  if(!Array.isArray(receipt.serviceMerges)||receipt.serviceMerges.length!==lanes.length)mismatches.push("reconciliation receipt must include every service merge");
  for(const[index,merge]of(Array.isArray(receipt.serviceMerges)?receipt.serviceMerges:[]).entries()){const shape=exactSchemaMismatches(merge,["repository","repositoryId","mergeCommit"],`reconciliation receipt serviceMerges[${index}]`);mismatches.push(...shape);if(!shape.length&&!([merge.repository,merge.repositoryId,merge.mergeCommit].every(trimmedString)))mismatches.push(`reconciliation receipt serviceMerges[${index}] is invalid`);}
  for(const lane of lanes){const proof=proofs.find((x)=>x.repositoryId===lane.repositoryId),merge=receipt.serviceMerges?.find((x)=>x.repositoryId===lane.repositoryId);if(!proof||!merge||merge.repository!==lane.repository||merge.mergeCommit!==proof.mergeCommit)mismatches.push(`reconciliation receipt service merge differs for ${lane.repository}`);}
  if(!Array.isArray(receipt.deltas)||!Array.isArray(receipt.adrCollisions))mismatches.push("reconciliation receipt semantic evidence must be arrays");
}
function planTendArchive(input) {
  const shape=exactSchemaMismatches(input,["story","publishedLanes","mergeProofs","owner","reconciliation","artifacts","sharedPointers","unresolvedFeedback"],"Tend archive inventory");if(shape.length)return stopAwaiting(shape.join("; "));
  const mismatches=[...exactSchemaMismatches(input.story,["id","lifecycle"],"Tend story"),...exactSchemaMismatches(input.owner,["ownerId","versioning","archiveTarget","writeMode"],"archive owner")];
  if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(input.story?.id||"")||input.story?.lifecycle!=="awaiting-review")mismatches.push("Tend requires an awaiting-review kebab-case story");
  const target=`.loom/archive/${input.story?.id}`,git=input.owner?.versioning==="git";
  if(!trimmedString(input.owner?.ownerId)||!["git","unversioned"].includes(input.owner?.versioning)||input.owner?.archiveTarget!==target||!normalizedRelativePath(input.owner?.archiveTarget)||input.owner?.writeMode!==(git?"git-local-integration":"atomic-owner-write"))mismatches.push("archive owner identity, target, or write mode is invalid");
  validatePublishedLanes(input.publishedLanes,mismatches);validateMergeProofs(input.mergeProofs,Array.isArray(input.publishedLanes)?input.publishedLanes:[],mismatches);
  validateReconciliationReceipt(input.reconciliation,input.story?.id,Array.isArray(input.publishedLanes)?input.publishedLanes:[],Array.isArray(input.mergeProofs)?input.mergeProofs:[],mismatches);
  if(typeof input.unresolvedFeedback!=="boolean"||input.unresolvedFeedback)mismatches.push("unresolved review feedback remains");
  if(!Array.isArray(input.artifacts)||input.artifacts.length===0)mismatches.push("archive artifacts must be nonempty");
  for(const[index,artifact]of(Array.isArray(input.artifacts)?input.artifacts:[]).entries()){const name=`artifacts[${index}]`;const as=exactSchemaMismatches(artifact,["path","content"],name);mismatches.push(...as);if(as.length)continue;const category=artifactCategory(artifact.path,target);if(!normalizedRelativePath(artifact.path)||!artifact.path.startsWith(`${target}/`)||!category)mismatches.push(`${name} path is outside the canonical story archive projection`);if(!trimmedString(artifact.content))mismatches.push(`${name} content must be nonempty`);else if(projectionLeak(artifact.content))mismatches.push(`${name} content contains local/runtime/private publication mechanics`);}
  const paths=Array.isArray(input.artifacts)?input.artifacts.map((a)=>a?.path):[];if(new Set(paths).size!==paths.length)mismatches.push("archive artifact paths must be unique");
  for(const category of ["STORY","PRD","issues","manifest"])if(!input.artifacts?.some((a)=>artifactCategory(a?.path||"",target)===category))mismatches.push(`archive artifacts must include ${category}`);
  if(git&&input.artifacts?.some((a)=>["CONTEXT","ADR"].includes(artifactCategory(a?.path||"",target))))mismatches.push("Git archive must point to shared CONTEXT/ADR, not duplicate full warp");
  if(!git)for(const category of ["CONTEXT","ADR"])if(!input.artifacts?.some((a)=>artifactCategory(a?.path||"",target)===category))mismatches.push(`unversioned archive must include full ${category}`);
  if(!Array.isArray(input.sharedPointers)||input.sharedPointers.length===0)mismatches.push("sharedPointers must be nonempty");
  const sharedPaths=new Set();
  for(const[index,pointer]of(Array.isArray(input.sharedPointers)?input.sharedPointers:[]).entries()){const name=`sharedPointers[${index}]`;const ps=exactSchemaMismatches(pointer,["category","path","contentDigest"],name);mismatches.push(...ps);if(ps.length)continue;if(!["CONTEXT","ADR"].includes(pointer.category)||!normalizedRelativePath(pointer.path)||!/^[a-f0-9]{64}$/.test(pointer.contentDigest))mismatches.push(`${name} is invalid`);else{const canonicalPath=pointer.path.split("/").join("/");if(sharedPaths.has(canonicalPath))mismatches.push(`${name} duplicates canonical shared pointer path ${canonicalPath}`);sharedPaths.add(canonicalPath);}}
  if(!input.sharedPointers?.some((x)=>x.category==="CONTEXT")||!input.sharedPointers?.some((x)=>x.category==="ADR"))mismatches.push("sharedPointers must include relevant CONTEXT and ADR evidence");
  const manifestArtifact=input.artifacts?.find((a)=>artifactCategory(a?.path||"",target)==="manifest");
  if(manifestArtifact&&trimmedString(manifestArtifact.content)){try{const manifest=JSON.parse(manifestArtifact.content);const ms=exactSchemaMismatches(manifest,["story","owner","serviceMerges","sharedPointers"],"archive manifest");mismatches.push(...ms);if(!ms.length){const os=exactSchemaMismatches(manifest.owner,["commit","tree"],"archive manifest owner");mismatches.push(...os);const expectedMerges=input.reconciliation?.serviceMerges;if(manifest.story!==input.story?.id||!trimmedString(manifest.owner?.commit)||!trimmedString(manifest.owner?.tree)||manifest.owner.commit!==input.reconciliation?.ownerCommit||manifest.owner.tree!==input.reconciliation?.ownerTree||JSON.stringify(manifest.serviceMerges)!==JSON.stringify(expectedMerges)||JSON.stringify(manifest.sharedPointers)!==JSON.stringify(input.sharedPointers))mismatches.push("archive manifest must bind exact reconciliation owner commit/tree, service merge refs, and shared CONTEXT/ADR paths with SHA-256 digests");}}catch{mismatches.push("archive manifest must be valid JSON");}}
  if(mismatches.length)return stopAwaiting(mismatches.join("; "));
  const inventory=canonicalCopy(input);inventory.publishedLanes.sort((a,b)=>a.repository.localeCompare(b.repository));inventory.mergeProofs.sort((a,b)=>a.repository.localeCompare(b.repository));inventory.sharedPointers.sort((a,b)=>a.path.localeCompare(b.path));inventory.artifacts=inventory.artifacts.map(({path,content})=>({path,content,contentDigest:archiveArtifactDigest(content)})).sort((a,b)=>a.path.localeCompare(b.path));
  return{action:"ARCHIVE_PREVIEW",lifecycle:"awaiting-review",mutation:false,inventory,digest:publicationDigest(inventory),confirmationRequired:true,archiveBeforeDone:true,cleanupAuthorized:false,unversionedWarning:!git};
}
function digestRecords(artifacts){return artifacts.map(({path,contentDigest})=>({path,contentDigest})).sort((a,b)=>a.path.localeCompare(b.path));}
function exactDigestSet(value,expected,name){if(!Array.isArray(value)||value.length!==expected.length)return`${name} must exactly match projected artifacts`;const copy=canonicalCopy(value);for(const[i,x]of copy.entries()){const shape=exactSchemaMismatches(x,["path","contentDigest"],`${name}[${i}]`);if(shape.length)return shape.join("; ");}copy.sort((a,b)=>a.path.localeCompare(b.path));return JSON.stringify(copy)===JSON.stringify(expected)?null:`${name} differs from projected artifact digests`;}
function planTendArchiveResult(input) {
  const shape=exactSchemaMismatches(input,["inventory","confirmedDigest","currentInventory","archive"],"Tend archive result");if(shape.length)return stopAwaiting(shape.join("; "));
  const preview=planTendArchive(input.inventory),current=planTendArchive(input.currentInventory);if(preview.action!=="ARCHIVE_PREVIEW"||current.action!=="ARCHIVE_PREVIEW"||preview.digest!==input.confirmedDigest||preview.digest!==current.digest)return stopAwaiting("Tend archive inventory or confirmation is stale");
  const as=exactSchemaMismatches(input.archive,["writtenArtifacts","readBackArtifacts","writeMethod","integration"],"archive result");if(as.length)return stopAwaiting(as.join("; "));const expected=digestRecords(preview.inventory.artifacts);const written=exactDigestSet(input.archive.writtenArtifacts,expected,"writtenArtifacts"),read=exactDigestSet(input.archive.readBackArtifacts,expected,"readBackArtifacts");if(written||read)return stopAwaiting(written||read);
  const git=preview.inventory.owner.versioning==="git";
  if(git){const integrationShape=exactSchemaMismatches(input.archive.integration,["commit","tree","archiveDigest","parentCommit"],"archive integration");if(input.archive.writeMethod!=="git-local-integration"||integrationShape.length||!trimmedString(input.archive.integration?.commit)||!trimmedString(input.archive.integration?.tree)||input.archive.integration?.archiveDigest!==preview.digest||input.archive.integration?.parentCommit!==preview.inventory.reconciliation.ownerCommit)return stopAwaiting("Git archive integration evidence is invalid");}else if(input.archive.writeMethod!=="atomic-owner-write"||input.archive.integration!==null)return stopAwaiting("unversioned archive requires atomic-owner-write, exact full readback, and null integration");
  const mergeByRepo=new Map(preview.inventory.mergeProofs.map((proof)=>[proof.repositoryId,proof.mergeCommit]));const archiveReceipt={storyId:preview.inventory.story.id,archiveDigest:preview.digest,owner:canonicalCopy(preview.inventory.owner),ownerCommit:git?input.archive.integration.commit:preview.inventory.reconciliation.ownerCommit,ownerTree:git?input.archive.integration.tree:preview.inventory.reconciliation.ownerTree,lanes:preview.inventory.publishedLanes.map((lane)=>({...laneIdentity(lane),mergeCommit:mergeByRepo.get(lane.repositoryId)})),artifacts:expected,sharedPointers:preview.inventory.sharedPointers};
  return{action:"DONE",lifecycle:"done",cleanupAuthorized:false,archiveReceipt,unversionedWarning:!git};
}
function cleanupStop(reason){return{action:"STOP",lifecycle:"done",mutation:false,reason};}
function cleanupLaneIdentity(lane){return Object.fromEntries(["repository","repositoryId","nativeId","selector","branch","head"].map((key)=>[key,lane[key]]));}
function planTendCleanup(input) {
  const shape=exactSchemaMismatches(input,["archiveInventory","confirmedArchiveDigest","currentArchiveInventory","archive","currentLanes"],"Tend cleanup inventory");if(shape.length)return cleanupStop(shape.join("; "));
  const archived=planTendArchiveResult({inventory:input.archiveInventory,confirmedDigest:input.confirmedArchiveDigest,currentInventory:input.currentArchiveInventory,archive:input.archive});if(archived.action!=="DONE")return cleanupStop("same-story durable archive receipt is not proven");
  const mismatches=[];if(!Array.isArray(input.currentLanes))mismatches.push("currentLanes must be an array");const keys=["repository","repositoryId","nativeId","selector","branch","head","mergeCommit","clean","inactive","nativePresent","gitWorktreePresent","localBranchPresent"];
  for(const[index,lane]of(Array.isArray(input.currentLanes)?input.currentLanes:[]).entries()){const name=`currentLanes[${index}]`;const ls=exactSchemaMismatches(lane,keys,name);mismatches.push(...ls);if(ls.length)continue;for(const key of ["repository","repositoryId","nativeId","selector","branch","head","mergeCommit"])if(!trimmedString(lane[key]))mismatches.push(`${name} ${key} must be nonempty`);for(const key of ["clean","inactive","nativePresent","gitWorktreePresent","localBranchPresent"])if(typeof lane[key]!=="boolean")mismatches.push(`${name} ${key} must be boolean`);const receipt=archived.archiveReceipt.lanes.find((x)=>x.repositoryId===lane.repositoryId);if(!receipt||lane.repository!==receipt.repository||lane.nativeId!==receipt.nativeId||lane.branch!==receipt.branch||lane.head!==receipt.commit||lane.mergeCommit!==receipt.mergeCommit)mismatches.push(`${name} differs from archived lane identity or merge evidence`);if(lane.nativePresent!==lane.gitWorktreePresent)mismatches.push(`${name} has contradictory native/Git worktree presence`);if(lane.nativePresent&&!lane.localBranchPresent)mismatches.push(`${name} has a worktree without its local branch`);}
  const lanes=Array.isArray(input.currentLanes)?input.currentLanes:[];for(const field of ["repository","repositoryId","nativeId","selector","branch"])if(new Set(lanes.map((lane)=>lane?.[field])).size!==lanes.length)mismatches.push(`cleanup lane ${field}s must be unique`);if(lanes.length!==archived.archiveReceipt.lanes.length||archived.archiveReceipt.lanes.some((receipt)=>!lanes.some((lane)=>lane.repositoryId===receipt.repositoryId&&lane.nativeId===receipt.nativeId)))mismatches.push("current cleanup evidence must cover every archived lane exactly once");if(mismatches.length)return cleanupStop(mismatches.join("; "));
  const source={archiveInventory:canonicalCopy(input.archiveInventory),confirmedArchiveDigest:input.confirmedArchiveDigest,currentArchiveInventory:canonicalCopy(input.currentArchiveInventory),archive:canonicalCopy(input.archive),currentLanes:canonicalCopy(lanes).sort((a,b)=>a.repository.localeCompare(b.repository))};const actions=[],retained=[],completed=[];
  for(const lane of source.currentLanes){if(lane.nativePresent&&lane.gitWorktreePresent&&lane.localBranchPresent){if(lane.clean&&lane.inactive)actions.push({...cleanupLaneIdentity(lane),mergeCommit:lane.mergeCommit,kind:"remove-worktree-then-branch"});else retained.push({repository:lane.repository,reason:lane.clean?"active worktree":"dirty worktree"});}else if(!lane.nativePresent&&!lane.gitWorktreePresent&&lane.localBranchPresent){if(lane.inactive)actions.push({...cleanupLaneIdentity(lane),mergeCommit:lane.mergeCommit,kind:"delete-branch-only"});else retained.push({repository:lane.repository,reason:"active branch-only retry"});}else if(!lane.nativePresent&&!lane.gitWorktreePresent&&!lane.localBranchPresent)completed.push({...cleanupLaneIdentity(lane),kind:"completed"});}
  const inventory={source,archiveReceipt:archived.archiveReceipt,currentLanes:source.currentLanes,actions,retained,completed};return{action:actions.length?"CLEANUP_PREVIEW":"NOOP",lifecycle:"done",mutation:false,inventory,digest:publicationDigest(inventory),confirmationRequired:actions.length>0,actions,retained,completed,prohibitedEffects:["raw-git-worktree-remove","filesystem-remove","force","broad-reset","remote-delete"]};
}
function sameCleanupIdentity(result,action){return["repository","repositoryId","nativeId","selector","branch","head"].every((key)=>result[key]===action[key])&&result.actionKind===action.kind;}
function planTendCleanupResult(input) {
  const shape=exactSchemaMismatches(input,["inventory","confirmedDigest","currentInventory","results"],"Tend cleanup result");if(shape.length)return cleanupStop(shape.join("; "));const inventoryKeys=["source","archiveReceipt","currentLanes","actions","retained","completed"];const inventoryShape=exactSchemaMismatches(input.inventory,inventoryKeys,"cleanup confirmed inventory"),currentShape=exactSchemaMismatches(input.currentInventory,inventoryKeys,"cleanup current inventory");if(inventoryShape.length||currentShape.length)return cleanupStop([...inventoryShape,...currentShape].join("; "));
  const preview=planTendCleanup(input.inventory.source),current=planTendCleanup(input.currentInventory.source);if(preview.action!=="CLEANUP_PREVIEW"||current.action!=="CLEANUP_PREVIEW"||preview.digest!==input.confirmedDigest||current.digest!==input.confirmedDigest||JSON.stringify(input.inventory)!==JSON.stringify(preview.inventory)||JSON.stringify(input.currentInventory)!==JSON.stringify(current.inventory))return cleanupStop("cleanup action inventory or confirmation is stale");if(!Array.isArray(input.results))return cleanupStop("cleanup results must be an array");const outcomes=[],completedActions=[],remainingActions=[];let failed=false;
  for(const[index,result]of input.results.entries()){const action=preview.actions[index];if(!action||failed)return cleanupStop("cleanup results must be the exact action prefix and stop after first failure");const common=["repository","repositoryId","nativeId","selector","branch","head","actionKind","removal","branchDeletion","error"];const keys=action.kind==="remove-worktree-then-branch"?[...common.slice(0,8),"absence",...common.slice(8)]:common;const rs=exactSchemaMismatches(result,keys,`cleanup results[${index}]`);if(rs.length)return cleanupStop(rs.join("; "));if(!sameCleanupIdentity(result,action))return cleanupStop("cleanup result identity or action kind differs from confirmation");const branchShape=exactSchemaMismatches(result.branchDeletion,["method","status"],"cleanup branch deletion");if(branchShape.length||result.branchDeletion.method!=="git-branch-delete-merged-safe"||!["deleted","already-absent","failed","not-attempted"].includes(result.branchDeletion.status))return cleanupStop("cleanup branch deletion evidence is invalid");
    let success=false,partial=false,validFailure=false;
    if(action.kind==="remove-worktree-then-branch"){const removalShape=exactSchemaMismatches(result.removal,["command","attempted","succeeded"],"cleanup removal"),absenceShape=exactSchemaMismatches(result.absence,["orcaPresent","gitWorktreePresent"],"cleanup absence");if(removalShape.length||absenceShape.length||result.removal.command!=="orca worktree rm"||result.removal.attempted!==true)return cleanupStop("full cleanup requires exact native removal evidence");const worktreeGone=result.removal.succeeded===true&&result.absence.orcaPresent===false&&result.absence.gitWorktreePresent===false;success=worktreeGone&&["deleted","already-absent"].includes(result.branchDeletion.status)&&result.error===null;partial=worktreeGone&&result.branchDeletion.status==="failed"&&trimmedString(result.error);validFailure=result.removal.succeeded===false&&result.absence.orcaPresent===true&&result.absence.gitWorktreePresent===true&&result.branchDeletion.status==="not-attempted"&&trimmedString(result.error);if(success){completedActions.push({...cleanupLaneIdentity(action),kind:"remove-worktree",status:"completed"},{...cleanupLaneIdentity(action),kind:"delete-branch",status:"completed"});}else if(partial){completedActions.push({...cleanupLaneIdentity(action),kind:"remove-worktree",status:"completed"});remainingActions.push({...cleanupLaneIdentity(action),mergeCommit:action.mergeCommit,kind:"delete-branch-only"});}}
    else{const removalShape=exactSchemaMismatches(result.removal,["attempted"],"branch-only removal");if(removalShape.length||result.removal.attempted!==false)return cleanupStop("branch-only cleanup must not attempt worktree removal");success=["deleted","already-absent"].includes(result.branchDeletion.status)&&result.error===null;partial=result.branchDeletion.status==="failed"&&trimmedString(result.error);if(success)completedActions.push({...cleanupLaneIdentity(action),kind:"delete-branch",status:"completed"});else if(partial)remainingActions.push({...action});}
    if(!success&&!partial&&!validFailure)return cleanupStop("cleanup operation evidence is contradictory or unsafe");outcomes.push(canonicalCopy(result));failed=!success;
  }
  if(!input.results.length)return{action:"CLEANUP_ALLOWED",lifecycle:"done",storyId:preview.inventory.archiveReceipt.storyId,actions:preview.actions};const untouched=preview.actions.slice(outcomes.length);remainingActions.push(...untouched);const action=failed?(completedActions.length?"PARTIAL":"FAILURE"):(outcomes.length===preview.actions.length?"SUCCESS":"CONTINUE");return{action,lifecycle:"done",storyId:preview.inventory.archiveReceipt.storyId,archiveReceipt:preview.inventory.archiveReceipt,completedActions,remainingActions,outcomes,retryRequiresRefreshedRemainingInventory:failed};

}

module.exports = { classifyTendIntent, planTendReconciliation, planTendReconciliationResult, planTendArchive, planTendArchiveResult, planTendCleanup, planTendCleanupResult };
