"use strict";
const {computeCurrentBoundary,normalizeRepositories,parseBoundary}=require("./boundary.cjs");
const VERDICTS=new Set(["APPROVE","REJECT"]);
function line(value,name){if(typeof value!=="string"||!value.trim()||value!==value.trim()||/[\r\n|]/.test(value))throw new TypeError(`${name} invalid`);return value}
function review(value,name){if(!value||!VERDICTS.has(value.verdict)||Object.keys(value).sort().join(",")!=="checkerId,evidence,verdict")throw new TypeError(`${name} invalid`);return{verdict:value.verdict,checkerId:line(value.checkerId,`${name} identity`),evidence:line(value.evidence,`${name} evidence`)}}
function normalizeVerification(value){if(!value||typeof value!=="object")throw new TypeError("verification invalid");const required=["makerId","ticketDigest","repositories","boundaryDigest","spec","standards","human"],allowed=new Set(required);if(required.some(x=>!Object.hasOwn(value,x))||Object.keys(value).some(x=>!allowed.has(x)))throw new TypeError("verification fields invalid");if(!/^[a-f0-9]{64}$/i.test(value.ticketDigest)||!/^[a-f0-9]{64}$/i.test(value.boundaryDigest))throw new TypeError("verification digest invalid");return{makerId:line(value.makerId,"Maker"),ticketDigest:value.ticketDigest.toLowerCase(),repositories:normalizeRepositories(value.repositories),boundaryDigest:value.boundaryDigest.toLowerCase(),spec:review(value.spec,"Spec"),standards:review(value.standards,"Standards"),human:value.human===null?null:review(value.human,"Human")}}
function renderReview(name,x){return `${name}: ${x.verdict} | ${x.checkerId} | ${x.evidence}`}
function renderVerification(value){const v=normalizeVerification(value);return [`Maker: ${v.makerId}`,`Ticket digest: sha256:${v.ticketDigest}`,"Repositories:",...v.repositories.map(x=>`- ${x.key} | head ${x.head} | diff sha256:${x.diffDigest}`),`Boundary: sha256:${v.boundaryDigest}`,renderReview("Spec",v.spec),renderReview("Standards",v.standards),v.human?renderReview("Human",v.human):"Human: NOT REQUIRED"].join("\n")}
function parseReview(text,name){const m=new RegExp(`^${name}: (APPROVE|REJECT) \\| ([^|\\r\\n]+) \\| ([^\\r\\n]+)$`).exec(text);if(!m)throw new TypeError(`${name} line invalid`);return{verdict:m[1],checkerId:m[2],evidence:m[3]}}
function parseVerification(source){if(typeof source!=="string"||source!==source.trim())throw new TypeError("verification text not canonical");const lines=source.split("\n");if(!lines[0]?.startsWith("Maker: ")||!lines[1]?.startsWith("Ticket digest: sha256:")||lines[2]!=="Repositories:")throw new TypeError("verification order invalid");let i=3;const repositories=[];while(lines[i]?.startsWith("- ")){const m=/^- ([^|\r\n]+) \| head ([a-f0-9]{40,64}) \| diff sha256:([a-f0-9]{64})$/.exec(lines[i++]);if(!m)throw new TypeError("repository line invalid");repositories.push({key:m[1],head:m[2],diffDigest:m[3]})}const b=/^Boundary: sha256:([a-f0-9]{64})$/.exec(lines[i++]||"");if(!b)throw new TypeError("Boundary line invalid");const value={makerId:lines[0].slice(7),ticketDigest:lines[1].slice(22),repositories,boundaryDigest:b[1],spec:parseReview(lines[i++]||"","Spec"),standards:parseReview(lines[i++]||"","Standards")};const human=lines[i++]||"";value.human=human==="Human: NOT REQUIRED"?null:parseReview(human,"Human");if(i!==lines.length)throw new TypeError("unknown or duplicate verification content");const normalized=normalizeVerification(value);if(renderVerification(normalized)!==source)throw new TypeError("verification text not canonical");return normalized}
function checkVerification(ticket,source,currentBoundary){let v,b;try{v=parseVerification(source);b=parseBoundary(currentBoundary)}catch(error){return{ok:false,errors:[error.message]}}const errors=[];if(v.ticketDigest!==b.ticketDigest)errors.push("Ticket digest stale");if(JSON.stringify(v.repositories)!==JSON.stringify(b.repositories))errors.push("Repositories stale");if(v.boundaryDigest!==b.digest)errors.push("Boundary stale");if(v.spec.verdict!=="APPROVE")errors.push("Spec APPROVE required");if(v.standards.verdict!=="APPROVE")errors.push("Standards APPROVE required");const identities=[v.makerId,v.spec.checkerId,v.standards.checkerId];if(new Set(identities).size!==identities.length)errors.push("Maker and checkers must be distinct");const humanRequired=ticket.humanApproval==="required";if(humanRequired&&!v.human)errors.push("Human APPROVE required");if(!humanRequired&&v.human)errors.push("Human must be NOT REQUIRED by Ticket policy");if(v.human&&v.human.verdict!=="APPROVE")errors.push("Human must APPROVE when present");if(v.human&&identities.includes(v.human.checkerId))errors.push("Human identity must be distinct");return{ok:!errors.length,errors,verification:v}}
function checkTicket(root,ticket){let boundary;try{boundary=computeCurrentBoundary(root,ticket)}catch(error){return{ok:false,errors:[`cannot observe boundary: ${error.message}`]}}return checkVerification(ticket,ticket.sections.Verify,boundary)}
module.exports={checkTicket,checkVerification,normalizeVerification,parseVerification,renderVerification};
