#!/usr/bin/env node
import {readFileSync} from "node:fs";
import {resolve} from "node:path";
import {createHash} from "node:crypto";
import {parseJudgeResponse,assertJudgeRequest,RUBRIC} from "./judge.mjs";
import {requireFreshApproval} from "../approval.mjs";
export const PILOT_BUDGET=Object.freeze({cases:6,runsPerArm:2,judges:1,maxSeconds:120,maxCostUsd:0});
export const DIMENSIONS=Object.freeze([...RUBRIC.dimensions]);
export const CASES=Object.freeze([{id:"unclear-export",prompt:"We need an export that matches what users see. Help me decide what to build."},{id:"known-seam",prompt:"The ledger view already has a filtered query. We need a reversible local export proof."},{id:"security-boundary",prompt:"A public export crosses a security boundary and may expose customer data. Help frame the decision."},{id:"wrong-object",prompt:"The button is slow, but the unmet outcome may be a stale filtered view. Help identify the real object."},{id:"domain-language",prompt:"Our terms account, workspace, and member are used inconsistently in the export flow."},{id:"load-bearing-choice",prompt:"Choose between a complete export and a predictable filtered export for a shared workflow."}]);
const root=resolve(import.meta.dirname,"../.."),hash=v=>createHash("sha256").update(v).digest("hex"),exact=(v,keys)=>v&&typeof v==="object"&&!Array.isArray(v)&&JSON.stringify(Object.keys(v).sort())===JSON.stringify([...keys].sort());
const planIdentity=(name,seed)=>Object.freeze({name,ref:"PLAN-only-"+name,commit:hash(seed+":commit"),contentDigest:hash(seed+":content"),planOnly:true});
export function semanticCanary(text=readFileSync(resolve(root,"skills/loom-grill/INTERVIEW.md"),"utf8")){const source=text.toLowerCase().replace(/[^a-z0-9]+/g," ");const required=[/observed failure or unmet outcome.*named cost owner/,/admit a question only when its answer can change/,/resolve prerequisite dependencies in order/,/select the smallest depth from observed signals/,/terminology entity relationship or code vocabulary signals/,/recommendations state their evidence and consequences the user owns the trade off/,/read back the proportional minimum/,/stop when no admissible user owned questions remain/,/objective resolved outcome.*selected depth/,/grill never writes story prd or ticket artifacts/];const missing=required.map((pattern,index)=>pattern.test(source)?null:["premise","question admission","dependency","depth","domain trigger","recommendation ownership","proportional readback","stop","compact handoff","authority"][index]).filter(Boolean);if(missing.length)throw Error("Grill semantic canary failed: "+missing.join(", "));return{pass:true,checks:required.length};}
export function buildPrompt(testCase){if(!testCase?.id||!testCase.prompt)throw Error("invalid pilot case");return testCase.prompt+"\\n\\nApply the Grill reference. Return the interview readback and stop decision.";}
export const promptHash=prompt=>hash(prompt);
export function assertEquivalentPrompts(a,b){if(a.length!==b.length||a.some((x,i)=>x!==b[i]))throw Error("control and candidate prompts must be equivalent");}
export function assertBudget(plan,budget=PILOT_BUDGET){if(!exact(plan,["cases","runsPerArm","judges","maxSeconds","maxCostUsd"])||plan.cases>budget.cases||plan.runsPerArm>budget.runsPerArm||plan.judges>budget.judges||plan.maxSeconds>budget.maxSeconds||plan.maxCostUsd>budget.maxCostUsd)throw Error("pilot budget exceeded");return true;}
export const assertFreshApproval=(approval,now=Date.now())=>requireFreshApproval(approval,{scope:"grill-pilot",budget:PILOT_BUDGET,now});
export function buildPilotManifest(){const control=planIdentity("control","loom-grill-control-v7"),candidate=planIdentity("candidate","loom-grill-candidate-v7"),mapping=Object.freeze({A:"control",B:"candidate"}),rows=CASES.flatMap(c=>Array.from({length:PILOT_BUDGET.runsPerArm},(_,i)=>({caseId:c.id,run:i+1,promptHash:promptHash(buildPrompt(c)),provenanceKey:hash(c.id+":"+(i+1)+":"+promptHash(buildPrompt(c)))})));return Object.freeze({control,candidate,mapping,rows:Object.freeze(rows),budget:PILOT_BUDGET,rubricVersion:"behavior-v1"});}
export function buildRunPlan(){const m=buildPilotManifest();return Object.freeze(m.rows.flatMap(r=>["A","B"].map(arm=>Object.freeze({...r,arm,identity:m[m.mapping[arm]]}))));}
export function createBlindedPacket({caseId,prompt,outputs,run=1,rubricVersion="behavior-v1"}){const packet={caseId,run,outputs,promptHash:promptHash(prompt),rubricVersion};assertJudgeRequest(packet);return Object.freeze(packet);}
export const assertBlinded=packet=>(assertJudgeRequest(packet),true);
export function judgeVerdict(scores){return scores.loadBearingDecisionOpened?{questionCountGuardrail:"not_penalized",reason:"new load-bearing decision opened"}:{questionCountGuardrail:scores.questions<=scores.baselineQuestions?"pass":"review"};}
export function scorePilot(responses,manifest=buildPilotManifest()){if(!Array.isArray(responses)||responses.length!==manifest.rows.length)throw Error("pilot judge response count is invalid");const expected=new Map(manifest.rows.map(r=>[r.caseId+":"+r.run,r])),seen=new Set(),judgments=[];for(const value of responses){const response=parseJudgeResponse(value),key=response.caseId+":"+response.run,row=expected.get(key);if(!row)throw Error("undeclared or untrusted pilot provenance");if(seen.has(key))throw Error("duplicate pilot judge response");if(response.promptHash!==row.promptHash)throw Error("wrong canonical case prompt provenance");if(response.rubricVersion!==manifest.rubricVersion)throw Error("wrong rubric provenance");seen.add(key);const total=s=>Object.values(response.scores[s]).filter(Number.isInteger).reduce((a,b)=>a+b,0),verdict=total("A")===total("B")?"tie":total("A")>total("B")?"A":"B";if(response.verdict!==verdict)throw Error("judge verdict does not match scores");judgments.push(response);}if(seen.size!==manifest.rows.length)throw Error("pilot judge response matrix is incomplete");const totals={A:0,B:0};for(const j of judgments)for(const s of ["A","B"])totals[s]+=Object.values(j.scores[s]).filter(Number.isInteger).reduce((a,b)=>a+b,0);return Object.freeze({judgments,totals,verdict:totals.A===totals.B?"tie":totals.A>totals.B?"A":"B",questionCountGuardrail:judgments.some(j=>j.scores.A.loadBearingDecisionOpened||j.scores.B.loadBearingDecisionOpened)?"not_penalized":"pass"});}
export function dryRun(){semanticCanary();const prompts=CASES.map(buildPrompt);assertEquivalentPrompts(prompts,CASES.map(buildPrompt));const plan={cases:CASES.length,runsPerArm:PILOT_BUDGET.runsPerArm,judges:PILOT_BUDGET.judges,maxSeconds:PILOT_BUDGET.maxSeconds,maxCostUsd:PILOT_BUDGET.maxCostUsd};assertBudget(plan);const manifest=buildPilotManifest();return Object.freeze({mode:"dry-run",manifest,runPlan:buildRunPlan(),...plan,budget:PILOT_BUDGET,dimensions:DIMENSIONS,rubric:RUBRIC,externalExecution:false,outputs:[],scores:[],verdict:null,promptHashes:prompts.map(promptHash)});}
if(import.meta.main){if(process.argv.slice(2).includes("--dry-run"))process.stdout.write(JSON.stringify(dryRun())+"\n");else{console.error("BLOCKED: live Grill pilot requires an approved external executor and fresh host approval immediately before execution; this CLI never fabricates scoring.");process.exitCode=2;}}
